### ISSUE TITLE
最新commit运行1天后出现问题！

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#100]
问题：
1、会导致原来的www.youtube.com自动变成youtube.com，无法打开油管；
2、在github通过wget下载raw文件时，点击某个文件的raw无法登陆打开网页，导致无法wget方式下载，报错提示为tls问题；
3、无法svn export方式下载仓库文件夹，提示语第2点一样。

**Comment by mokeyish** [comment]
地址变更是 http 协议的 301 或者 302 跳转，跟 dns 没关系。

解析不了，提供信息不足，可能是浏览器本身缓存，或者配置无法获取 upstream 的 ip，这是要我猜？

**Comment by mokeyish** [comment]
#110 重复
