### ISSUE TITLE
请问这两行代码有什么区别！

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#108]
https://github.com/mokeyish/smartdns-rs/blob/main/src/dns_conf.rs#L1887-L1888

**Comment by mokeyish** [comment]
无区别，两个一样，表示加不 s 都行

**Comment by zxlhhyccc** [comment]
> 无区别，两个一样，表示加不 s 都行

还有个问题，原版官方脚本中这两行不加判断可以正常运行而你的不行，上次我在你仓库加了判断没问题，大佬你看看你的源码应该改哪里？
https://github.com/pymumu/smartdns/blob/master/package/openwrt/files/etc/init.d/smartdns#L299-L300

**Comment by mokeyish** [comment]
![图片](https://user-images.githubusercontent.com/16131917/229554014-2559b89a-104f-40ef-89fe-5446920e2db2.png)



https://github.com/mokeyish/smartdns-rs/blob/1307bc92151d362696b7e74512ab7b7111ede54c/src/dns_conf.rs#L1534

**Comment by zxlhhyccc** [comment]
> ![图片](https://user-images.githubusercontent.com/16131917/229554014-2559b89a-104f-40ef-89fe-5446920e2db2.png)
> 
> ![图片](https://user-images.githubusercontent.com/16131917/229554564-11ce8615-dc4b-446c-8017-680ec4d7a04c.png)
> 
> https://github.com/mokeyish/smartdns-rs/blob/1307bc92151d362696b7e74512ab7b7111ede54c/src/dns_conf.rs#L1534

·"-a" | "-address" => { ·这个改一下可以，我说的是：原版官方脚本中这两行不加判断可以正常运行而你的不行，上次我在你仓库加了判断没问题，大佬你看看你的源码应该改哪里？https://github.com/pymumu/smartdns/blob/master/package/openwrt/files/etc/init.d/smartdns#L299-L300

**Comment by mokeyish** [comment]
加上 `--address` 识别呗

**Comment by mokeyish** [comment]
就是这个 `domain-rules /domain-set:domain-block-list/ --address #` 这个识别到啊

**Comment by zxlhhyccc** [comment]
> 就是这个 `domain-rules /domain-set:domain-block-list/ --address #` 这个识别到啊

这个是屏蔽域名的设置，而那个是域名转发的设置，不一样啊

**Comment by mokeyish** [comment]
从这一行，一行读取，解析

https://github.com/mokeyish/smartdns-rs/blob/1307bc92151d362696b7e74512ab7b7111ede54c/src/dns_conf.rs#L1750

**Comment by mokeyish** [comment]
最下面有单元测试，vscode 可以点击调试，一行一行看解析过程。

**Comment by zxlhhyccc** [comment]
> 最下面有单元测试，vscode 可以点击调试，一行一行看解析过程。

不会玩vscode 啊

**Comment by mokeyish** [comment]
> 不会玩vscode 啊


可以明天或后天找时间给你远程桌面演示五分钟足够了，比 shell 脚本简单，还有智能提示。shell 到现在，我也没能随心所欲写，都是看片段改的。

**Comment by zxlhhyccc** [comment]
大佬，可以帮忙远程指导吗？

**Comment by mokeyish** [comment]
可以啊，你开个腾讯会议，把连接发给我。

**Comment by mokeyish** [comment]
都可以哦。

**Comment by zxlhhyccc** [comment]
> 都可以哦。

https://meeting.tencent.com/dm/LlPZxLuVtzzq

**Comment by mokeyish** [comment]
[dns_conf.zip](https://github.com/mokeyish/smartdns-rs/files/11150074/dns_conf.zip)

**Comment by zxlhhyccc** [comment]
大佬，问题解决了。。。。
现在还有一个文件情况，如果加上2个杠的后，这里应该怎么改：
![image](https://user-images.githubusercontent.com/45259624/229851597-9e39af7e-40d4-4ef4-9b7c-02c4bad9d623.png)
![image](https://user-images.githubusercontent.com/45259624/229851825-4b2c06d0-95f2-4c41-be95-e6de5c663839.png)

**Comment by mokeyish** [comment]
其他地方不用改的，加单元测试看看

**Comment by mokeyish** [comment]
是的

**Comment by zxlhhyccc** [comment]
> 其他地方不用改的，加单元测试看看

好的，但这几个模块是不是还是有问题？
![image](https://user-images.githubusercontent.com/45259624/229853325-3334e60c-c432-4de6-b8c9-11be20cdb0d1.png)

**Comment by mokeyish** [comment]
看着像有问题，怎么会 unknown option 呢。有改其他地方？只加 `| --long-name`.

**Comment by zxlhhyccc** [comment]
> 看着像有问题，怎么会 unknown option 呢。有改其他地方？只加 `| --long-name`.

没动其他地方，我只是把你的文件改成："-a" | "-address" | "--address"

**Comment by mokeyish** [comment]
没问题，时没实现 `-speed-check-mode` 的解析。你的配置文件错了？原版文档没写支持这种配置的。


![图片](https://user-images.githubusercontent.com/16131917/229854551-76195938-b75c-4b1c-ad6e-30acb9124767.png)

**Comment by zxlhhyccc** [comment]
> 没问题，是没实现 `-speed-check-mode` 的解析。你的配置文件错了？原版文档没写支持这种配置的。
> 
> ![图片](https://user-images.githubusercontent.com/16131917/229854551-76195938-b75c-4b1c-ad6e-30acb9124767.png)

那问题是，如果只对国内dns测速，该怎么写？

**Comment by zxlhhyccc** [comment]
大佬，`dns_conf.rs`可以PR吗？

**Comment by mokeyish** [comment]
能改进这个程序的，当然欢迎 PR 了，你提就是了。

**Comment by mokeyish** [comment]
#122 已修复，兼容解析。
