### ISSUE TITLE
大佬，确实会修改浏览器收藏的网址，请问什么原因？

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#110]
我谷歌浏览器安装时自动收藏的网址是：www.youtube.com，但运行smartdns后（端口53和5335），网址却变成：youtube.com：
![image](https://user-images.githubusercontent.com/45259624/229972990-1332419c-94b3-4521-a0f7-b79af43f9538.png)

**Comment by mokeyish** [comment]
这是 http 协议处理的
https://zh.m.wikipedia.org/zh-cn/HTTP_302

域名解析 ip ，该 ip 机器，有 http 301/302 跳转规则。

**Comment by mokeyish** [comment]
你用命令 `curl -v baidu.com`

也可以看到，百度也加了地址跳转。

**Comment by zxlhhyccc** [comment]
测试了一下官方版本，不存在跳转问题，大佬能否修复一下？

**Comment by mokeyish** [comment]
那你定位一下，两个版本查询返回的 IP 是什么，确定 IP 是哪个上游服务器返回的。一个有问题，一个没问题，那就是上游服务器配置顺序，查询耗时，等导致取了一个有问题的 IP。

**Comment by zxlhhyccc** [comment]
> 那你定位一下，两个版本查询返回的 IP 是什么，确定 IP 是哪个上游服务器返回的。一个有问题，一个没问题，那就是上游服务器配置顺序，查询耗时，等导致取了一个有问题的 IP。
> 
> 无法重现的问题，就是无法修复的。

大佬，你能把你的自定义配置发我测试么？

**Comment by mokeyish** [comment]
在这里，https://github.com/mokeyish/smartdns-rs/blob/main/tests/example/smartdns.conf

**Comment by zxlhhyccc** [comment]
大佬，我找到原因了，我配置了运营商的dns导致的，去掉后就正常了。。。
