### ISSUE TITLE
win11的系统dns设置要怎么设置呀？

### ISSUE THREAD

**Issue by z20s11q** [mokeyish/smartdns-rs#125]
![image](https://user-images.githubusercontent.com/73921008/234044333-ce38a746-fa5a-4c77-ac74-55d946acb6c0.png)
这里的dns设置应该怎么设置？然后配置文件的bind应该怎么写比较好？

我在win11的系统设置里，ipv4的dns设置的127.0.0.1，然后配置文件bind的[::]:53，浏览器无法解析dns

**Comment by mokeyish** [comment]
建议前台运行一下程序先，可能端口被占用程序没起来。wsl 会占用 53 端口的，如果被占用，建议写具体 ip 地址，如
```ini
# ipv4 本机地址
bind 127.0.0.1:53
# ipv6 本机地址
bind [::1]:53
```
