### ISSUE TITLE
无法监听[::1]:53以外的地址

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#138]
windows系统，在最新版本的smartdns中，如果我在smartdns.conf中将监听地址设置为[::]:53或[::1]:53，则当我设置本地dns为[::1]:53的时候，smartdns可以生效并正常运行（使用nslookup命令可以看到）；
但如果我在smartdns.conf中将监听地址设置为[::2]:53或其他地址，并将本地dns也设置为该地址，使用nslookup命令无法看到smartdns，并且此时电脑无法正常上网。
此外，在设置为[::]:53时也有一定概率在运行一段时间后无法上网。

**Comment by mokeyish** [comment]
你电脑又 ipv6 地址？建议写 127.0.0.1 地址，其他地址可能会跟 wsl 冲突。

**Comment by zbc258** [comment]
> 你电脑又 ipv6 地址？建议写 127.0.0.1 地址，其他地址可能会跟 wsl 冲突。

您好，我电脑上并没有wsl或者其他软件，也没有查询到本机ipv6地址，目前都设置为[::1]:53后使用nslookup命令提示超时，但是使用wireshark抓包可以看到有来自不同dns服务器的解析结果。

**Comment by mokeyish** [comment]
没有 ipv6 就不要用 `[::1]:53` ,改成 ipv4 的 `127.0.0.1:53` 来监听。

如果想绑定到指定网卡 `以太网1` 的 ip 就写成 `0.0.0.0:53@以太网1`

**Comment by zbc258** [comment]
> 没有 ipv6 就不要用 `[::1]:53` ,改成 ipv4 的 `127.0.0.1:53` 来监听。
> 
> 如果想绑定到指定网卡 `以太网1` 的 ip 就写成 `0.0.0.0:53@以太网1`

不行啊哥，改成ipv4还是能用不能看😂，nslookup提示超时，但是抓包可以看见返回不同的dns地址

**Comment by mokeyish** [comment]
用这个配置：

```conf

# 在本地 53 端口监听
bind 127.0.0.1:53  

# 配置 bootstrap-dns，如不配置则调用系统的，建议配置，这样就加密了。
server https://223.5.5.5/dns-query  -bootstrap-dns -exclude-default-group

# 配置默认上游服务器
server https://dns.alidns.com/dns-query
server https://doh.pub/dns-query

# 配置公司（家里）上游服务器
server 192.168.1.1 -exclude-default-group -group office

# 以 ofc 结尾的域名转发至 office 分组进行解析
nameserver /ofc/office

# 设置域名的静态 IP
address /test.example.com/1.2.3.5

# 屏蔽域名（广告屏蔽）
address /ads.example.com/#
```

**Comment by zbc258** [comment]
> 用这个配置：
> 
> ```
> 
> # 在本地 53 端口监听
> bind 127.0.0.1:53  
> 
> # 配置 bootstrap-dns，如不配置则调用系统的，建议配置，这样就加密了。
> server https://223.5.5.5/dns-query  -bootstrap-dns -exclude-default-group
> 
> # 配置默认上游服务器
> server https://dns.alidns.com/dns-query
> server https://doh.pub/dns-query
> 
> # 配置公司（家里）上游服务器
> server 192.168.1.1 -exclude-default-group -group office
> 
> # 以 ofc 结尾的域名转发至 office 分组进行解析
> nameserver /ofc/office
> 
> # 设置域名的静态 IP
> address /test.example.com/1.2.3.5
> 
> # 屏蔽域名（广告屏蔽）
> address /ads.example.com/#
> ```

可以了，非常感谢！

**Comment by mokeyish** [comment]
你应该是你原来配置上游服务器有些是没用的，或者太多了。

**Comment by zbc258** [comment]
> 你应该是你原来配置上游服务器有些是没用的，或者太多了。

很可能是，对比了一下发现配的国外服务器太多而且没有一个bootstrap，加上bootstrap之后我原来的配置也没问题了，而且解析变快了很多。
