### ISSUE TITLE
编译报错 error[E0592]: duplicate definitions with name `is_soa`

### ISSUE THREAD

**Issue by wacdev** [mokeyish/smartdns-rs#142]
另外 release中没有  x86_64 linux gun
https://github.com/mokeyish/smartdns-rs/releases

```
   Compiling pnet_macros v0.31.0
error[E0592]: duplicate definitions with name `is_soa`
   --> /opt/rust/git/checkouts/trust-dns-97a7602ad159d348/41b6e33/crates/proto/src/rr/record_data.rs:59:17
    |
59  | #[derive(Debug, EnumAsInner, PartialEq, Clone, Eq)]
    |                 ^^^^^^^^^^^ duplicate definitions for `is_soa`
...
752 |     pub fn is_soa(&self) -> bool {
    |     ---------------------------- other definition for `is_soa`
    |
    = note: this error originates in the derive macro `EnumAsInner` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0592`.
error: could not compile `trust-dns-proto` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...

```

**Comment by wacdev** [comment]
另外最好能有一个默认的 systemctl的配置

**Comment by mokeyish** [comment]
> 另外 release中没有 x86_64 linux gun https://github.com/mokeyish/smartdns-rs/releases
> 
> ```
>    Compiling pnet_macros v0.31.0
> error[E0592]: duplicate definitions with name `is_soa`
>    --> /opt/rust/git/checkouts/trust-dns-97a7602ad159d348/41b6e33/crates/proto/src/rr/record_data.rs:59:17
>     |
> 59  | #[derive(Debug, EnumAsInner, PartialEq, Clone, Eq)]
>     |                 ^^^^^^^^^^^ duplicate definitions for `is_soa`
> ...
> 752 |     pub fn is_soa(&self) -> bool {
>     |     ---------------------------- other definition for `is_soa`
>     |
>     = note: this error originates in the derive macro `EnumAsInner` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> For more information about this error, try `rustc --explain E0592`.
> error: could not compile `trust-dns-proto` (lib) due to previous error
> warning: build failed, waiting for other jobs to finish...
> ```

应该是上游类库发生了破坏性更新导致的。


为啥要 gnu 呢？musl 不可以吗？

**Comment by mokeyish** [comment]
> 另外最好能有一个默认的 systemctl的配置

你用 smartdns service install 会安装 systemctl 的服务的。

**Comment by wacdev** [comment]
> > 另外 release中没有 x86_64 linux gun https://github.com/mokeyish/smartdns-rs/releases
> > ```
> >    Compiling pnet_macros v0.31.0
> > error[E0592]: duplicate definitions with name `is_soa`
> >    --> /opt/rust/git/checkouts/trust-dns-97a7602ad159d348/41b6e33/crates/proto/src/rr/record_data.rs:59:17
> >     |
> > 59  | #[derive(Debug, EnumAsInner, PartialEq, Clone, Eq)]
> >     |                 ^^^^^^^^^^^ duplicate definitions for `is_soa`
> > ...
> > 752 |     pub fn is_soa(&self) -> bool {
> >     |     ---------------------------- other definition for `is_soa`
> >     |
> >     = note: this error originates in the derive macro `EnumAsInner` (in Nightly builds, run with -Z macro-backtrace for more info)
> > 
> > For more information about this error, try `rustc --explain E0592`.
> > error: could not compile `trust-dns-proto` (lib) due to previous error
> > warning: build failed, waiting for other jobs to finish...
> > ```
> 
> 应该是上游类库发生了破坏性更新导致的。
> 
> 为啥要 gnu 呢？musl 不可以吗？

 我用的是ubuntu，musl可以用吗？

**Comment by zxlhhyccc** [comment]
> 应该是上游类库发生了破坏性更新导致的。
> 
> 为啥要 gnu 呢？musl 不可以吗？

openwrt的master分支下使用musl1.2.4版本只要补齐64-bit就能正常编译。。。。
musl1.2.4版本补丁在此：
https://github.com/openwrt/openwrt/pull/12667

**Comment by mokeyish** [comment]
duplicate definitions for `is_soa` 已经修复 #148
