### ISSUE TITLE
Looking for a good starting configuration

### ISSUE THREAD

**Issue by SamTV12345** [mokeyish/smartdns-rs#143]
Hi, 

I'm looking for a good starting configuration I can use to configure this dns server. I'd like to have 1.1.1.1, 8.8.8.8 and 9.9.9.9 as upstream servers

This is my configuration:
```
bind-tcp [::]:53
bind [::]:53
cache-persist yes
prefetch-domain yes
serve-expired yes
rr-ttl 32
rr-ttl-min 16
rr-ttl-max 64
log-level info
server 1.1.1.1
```

Unfortunately nothing happens when I point my iPhone to the ip address of the Pi4.

**Comment by mokeyish** [comment]
Hi, What's the OS you are running on?

Listen to all addresses on windows, which may conflict with WSL.

**Comment by mokeyish** [comment]
Check that it works, the easiest way is to query ptr.
```shell
dig @127.0.0.0 -p 53 ptr whoami.
```

I will return the server-name in the configuration or the host name.

**Comment by mokeyish** [comment]
Here is the configuration that may suitable for you.

```ini

# Listen on local port 53
bind 127.0.0.1:53  

# Configure bootstrap-dns, if not configured, call the system_conf, 
# it is recommended to configure, so that it will be encrypted.
server https://1.1.1.1/dns-query  -bootstrap-dns -exclude-default-group

# Configure default upstream server
server https://cloudflare-dns/dns-query
server https://dns.quad9.net/dns-query

# Set static IP for domain name
address /test.example.com/1.2.3.5

# Block Domains (Ad Blocking)
address /ads.example.com/#


```

**Comment by mokeyish** [comment]
For more advanced configurations, Please refer to 

https://pymumu.github.io/smartdns/en/config/basic-config/

**Comment by SamTV12345** [comment]
Thanks that worked without a problem.

**Comment by SamTV12345** [comment]
Closed. As I could find a good starting point for my home dns. Thanks.
