### ISSUE TITLE
Log message at the beginning: _client::bootstrap:1055

### ISSUE THREAD

**Issue by SamTV12345** [mokeyish/smartdns-rs#145]
2023-05-31 19:11:02.599:WARN:smartdns::dns_client::bootstrap:1055: read system conf failed, Error parsing resolv.conf: Malformed label: :q

I used the following configuration.

[smartdns (2).txt](https://github.com/mokeyish/smartdns-rs/files/11618206/smartdns.2.txt)

I did some tests and tried to breach through. Almost all urls where blocked correctly. So well done.

I also noticed that some urls can leak through. E.g. the url in line 2569 can somehow redirect to country.domain

**Comment by mokeyish** [comment]
Hi, what's content in the `/etc/resolve.conf`

**Comment by SamTV12345** [comment]
This is the content of /etc/resolve.conf
# DNS requests are forwarded to the host. DHCP DNS options are ignored.
nameserver 192.168.65.7

That should be generated by Docker
You can try the docker image at samuel19982/dns:latest

**Comment by mokeyish** [comment]
It seems that it is no problem with the resolve.conf.

The parser code locates at https://github.com/bluejekyll/trust-dns/blob/main/crates/resolver/src/system_conf/unix.rs

**Comment by SamTV12345** [comment]
Thanks. I'll report that to the trustdns project.

**Comment by mokeyish** [comment]
Hi, What's your hostname? it may contain `***q`

**Comment by SamTV12345** [comment]
The hostname is k3s. 

The latest release contains another log message: WARN:smartdns::dns_client:575: lookup ip: cloudflare-dns failed, Forward resolution error: no record found for Query { name: Name("cloudflare-dns."), query_type: AAAA, query_class: IN }

**Comment by mokeyish** [comment]
The boostrap-dns is very important for first time to fetch upstream server's ip address.

```ini
# Configure bootstrap-dns, if not configured, call the system_conf, 
# it is recommended to configure, so that it will be encrypted.
server https://223.5.5.5/dns-query  -bootstrap-dns -exclude-default-group
```

**Comment by SamTV12345** [comment]
I still use above config. So no idea why it doesn't work.

**Comment by mokeyish** [comment]
> I still use above config. So no idea why it doesn't work.

please try add other bootstrap-dns

**Comment by SamTV12345** [comment]
I added another one and that is working. Seems like cloudlfare's is down.

**Comment by mokeyish** [comment]
> Error parsing resolv.conf: Malformed label: :q

It should be fixed by https://github.com/bluejekyll/trust-dns/pull/1999

**Comment by SamTV12345** [comment]
Yes I can confirm that this is now fixed. Thanks 😊.
