### ISSUE TITLE
Android下smartdns监听53端口会出现Segmentation fault及一些怪异行为

### ISSUE THREAD

**Issue by ArchGuyWu** [mokeyish/smartdns-rs#146]
我是在termux环境下进行的使用，并已执行了tsu命令，只要尝试监听53端口，smartdns就会要求读取/etc/resolv.conf文件(但是我填了上游dns服务器，没有必要读取才对)，在执行了termux-chroot命令后，无法读取的提示消失了，但是直接就Segmentation fault了；我也尝试过通过setcap给予绑定低位端口的权限，但是smartdns仍报告权限不够。
但是只要不试图监听53端口，就没有任何问题

**Comment by mokeyish** [comment]
安卓没有 1024 以下端口的权限。

**Comment by ArchGuyWu** [comment]
> 安卓没有 1024 以下端口的权限。

我已root

**Comment by ArchGuyWu** [comment]
而且之前用其它软件，如frp时，setcap设置一下就能监听1024以下端口

**Comment by mokeyish** [comment]
那你试试，端口转发？我手机没 root ，没得测试。

**Comment by ArchGuyWu** [comment]
> 那你试试，端口转发？我手机没 root ，没得测试。

不需要啊，按理说我setcap设置一下就能绑低位端口了

**Comment by ArchGuyWu** [comment]
但是我设置后smartdns还是提示权限不够

**Comment by mokeyish** [comment]
你把源码下载到你手机编译，跑看看。你这种情况，我也没法测试。

**Comment by ArchGuyWu** [comment]
> 你把源码下载到你手机编译，跑看看。你这种情况，我也没法测试。

好的

**Comment by mokeyish** [comment]
> 我是在termux环境下进行的使用，并已执行了tsu命令，只要尝试监听53端口，smartdns就会要求读取/etc/resolv.conf文件(但是我填了上游dns服务器，没有必要读取才对)，在执行了termux-chroot命令后，无法读取的提示消失了，但是直接就Segmentation fault了；我也尝试过通过setcap给予绑定低位端口的权限，但是smartdns仍报告权限不够。 但是只要不试图监听53端口，就没有任何问题

已添加如果设置了上游服务器（boostrapdns 必须是 ip 的，如果是域名的，还是得先解析域名才行），停止读取 `/etc/resolv.conf`。

https://github.com/mokeyish/smartdns-rs/commit/0575cb9472262decf8e30e99b7856fadbd6365bb
