### ISSUE TITLE
windows 下 service如何调用配置文件0.0

### ISSUE THREAD

**Issue by Adagior** [mokeyish/smartdns-rs#147]
windows 下 service如何调用配置文件0.0

smartdns service install 之后 如何调用配置文件  谢大佬

官方看不懂--
sc [<ServerName>] config [<ServiceName>] [type= {own | share | kernel | filesys | rec | adapt | interact type= {own | share}}] [start= {boot | system | auto | demand | disabled | delayed-auto}] [error= {normal | severe | critical | ignore}] [binpath= <BinaryPathName>] [group= <LoadOrderGroup>] [tag= {yes | no}] [depend= <dependencies>] [obj= {<AccountName> | <ObjectName>}] [displayname= <DisplayName>] [password= <Password>]

**Comment by mokeyish** [comment]
windows 服务默认位置：

https://github.com/mokeyish/smartdns-rs/blob/6daea68e61c0110898384e9e546aa0169732a785/src/service/windows/mod.rs#L17-L19
