### ISSUE TITLE
网络环境无ipv6地址的情况下仍在查询AAAA记录

### ISSUE THREAD

**Issue by ArchGuyWu** [mokeyish/smartdns-rs#150]
我在linux上使用了rust版的smartdns，最近感觉上网有点慢，于是用tcpdump看了一下，发现会查询AAAA记录，但我系统里没有ipv6地址

**Comment by mokeyish** [comment]
系统软件查的，你可以完全禁用它，提升速度。

**Comment by mokeyish** [comment]
当你开启 ipv6 soa. 这里判断到，就直接返回了，后续代码就不用跑了。

https://github.com/mokeyish/smartdns-rs/blob/2899e12c4fa8f448adc914100acef960d4d0c179/src/dns_mw_addr.rs#L101
