### ISSUE TITLE
监听[::1]:53地址出错

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#154]
系统：windows11专业版
在最新的0.6.2版本中，电脑有IPV6地址的情况下无法监听[::1]地址，nslookup命令显示超时，log中无报错记录；而相同配置文件，改为监听IPV4地址127.0.0.1:53时一切正常。
在ubuntu系统下试验，c语言版smartdns可以正常监听IPV6或是IPV4，所以应该不是我网络的问题。

**Comment by mokeyish** [comment]
无法监听，报什么错？

**Comment by zbc258** [comment]
> 无法监听，报什么错？

debug模式下log里没有错误提示，sever都排查过可以用，但是之前一直设定的监听[::1]地址，这几天用nslookup命令提示超时，改成127.0.0.1才能监听，想知道是什么原因。

**Comment by zbc258** [comment]
> 无法监听，报什么错？

很奇怪，昨天还只是监听不了[::1]，今天127.0.0.1的nslookup也显示超时了，但是debug模式下log里面没有任何报错，连警告也没有，配置文件都没动过。

**Comment by mokeyish** [comment]
检测参考 [#161](https://github.com/mokeyish/smartdns-rs/issues/161#issuecomment-1703672574)

**Comment by mokeyish** [comment]
windows 检测 udp 监听情况用 `netstat -an -p udp`。端口被其他占用了就是起不来的，我的也是被 WSL 占用了。

**Comment by zbc258** [comment]
> windows 检测 udp 监听情况用 `netstat -an -p udp`。端口被其他占用了就是起不来的，我的也是被 WSL 占用了。

0.6.4版本问题照旧，我用这条命令查看了::1:53端口并没有被任何应用占用，但是nslookup还是超时，wireshark看到是有解析的。如果conf里面改成监听127.0.0.1就都没问题，感谢你的耐心解答，我先就凑合着用吧。
