### ISSUE TITLE
smartdns 0.6.2 failed to build against rust 1.71.0

### ISSUE THREAD

**Issue by chenrui333** [mokeyish/smartdns-rs#159]
While [upgrading rust to 1.71.0](https://github.com/Homebrew/homebrew-core/pull/136514), we found some build failure as shown below:

```
error[E0277]: the trait bound `connection_provider::TokioRuntimeProvider: ConnectionProvider` is not satisfied in `dns_client::NameServer`
    --> src/dns_client.rs:1100:10
     |
1100 |     impl BootstrapResolver<NameServerGroup> {
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ within `dns_client::NameServer`, the trait `ConnectionProvider` is not implemented for `connection_provider::TokioRuntimeProvider`
     |
     = help: the trait `ConnectionProvider` is implemented for `GenericConnector<P>`
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5594719599/job/15158499681?pr=136514

**Comment by mokeyish** [comment]
Hello, would you kindly clear the build cache? It appears that there are no issues on my end.

**Comment by chenrui333** [comment]
yeah, looks like indeed flaky build issue, sorry about the confusion. Thanks!

**Comment by chenrui333** [comment]
for the record, this is my verification run https://github.com/chenrui333/github-action-test/actions/runs/5686978417 :)
