### ISSUE TITLE
nslookup命令是否已经不能检测samrtdnsn的运行情况？

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#161]
目前我在使用smartdns时，无论监听127.0.0.1:53还是::1:53，使用nslookup -querytype=ptr smartdns得到的结果都是“DNS request timed out. timeout was 2 seconds.”，但是在debug模式下都显示得到了正确的解析结果，使用wireshark抓包也可以看到返回了不同来源的dns解析结果。就算我将server减少到只有一个223.5.5.5，nslookup依然会报超时，但是dns解析是正常的。

**Comment by mokeyish** [comment]
监听 `[::1]:53`

同时修改网卡
- ipv4 的 dns 为 127.0.0.1
- ipv6 的 dns 为 ::1

![image](https://github.com/mokeyish/smartdns-rs/assets/16131917/8f2228c8-09ed-4509-a921-24d946c0f08c)

**Comment by mokeyish** [comment]
不改网卡下面这个命令也行：

```sh
nslookup -querytype=ptr smartdns. ::1
```

**Comment by zbc258** [comment]
> 不改网卡下面这个命令也行：
> 
> ```shell
> nslookup -querytype=ptr smartdns. ::1
> ```

非常玄幻，我因为某些原因重装了系统，conf不变还是监听::1:53，结果0.6.2版本的nslookup就能正确显示了；然后我看到版本更新装了0.6.4版本，再次提示超时；装回0.6.2版本，依然超时。

**Comment by mokeyish** [comment]
后面需要加上点的 `.`
