### ISSUE TITLE
windows版本配置键domain-rules的-no-cache 无效

### ISSUE THREAD

**Issue by gexiaopeng** [mokeyish/smartdns-rs#163]
我在windows10运行 smartdns-x86_64-pc-windows-msvc 版本，提示 domain-rules的-no-cache 属性无效。
那请问我怎么样让某些特定的域名不缓存，比如DDNS? （Linux正常）
运行结果:
![1](https://github.com/mokeyish/smartdns-rs/assets/7857056/58425fcf-7414-4d14-baaa-13b6897a5f86)
配置：
![2](https://github.com/mokeyish/smartdns-rs/assets/7857056/90517a86-e971-43e1-83ea-a43b6d039d22)

![33](https://github.com/mokeyish/smartdns-rs/assets/7857056/3da7df2a-7911-4dc7-bea5-e9c640df48cd)

**Comment by mokeyish** [comment]
目前没支持这个选项，我找时间加上了。

**Comment by gexiaopeng** [comment]
> 目前没支持这个选项，我找时间加上了。

麻烦把 serve-expired-prefetch-time  ，cache-checkpoint-time  属性也加上吧，现在windows版本这两个键不支持。
![QQ截图20230831091510](https://github.com/pymumu/smartdns/assets/7857056/28b97b28-4391-47b6-bb87-0bef00c39944)

**Comment by mokeyish** [comment]
`no-cache` 已经添加 https://github.com/mokeyish/smartdns-rs/commit/b25d7599c13eeb113dea0a737d3be6ee3de64c08

另外两个不是很重要，你另外开贴，后续有时间再看看
