### ISSUE TITLE
解析不稳定？

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#165]
win11专业版，从0.6.2升级到0.6.4之后，conf没有任何更改，加了-d后也没有报错，但电脑开始频繁断网，隔一段时间任务栏右下角就会显示网络连接断开，且nslookup命令一直显示超时。

**Comment by zbc258** [comment]
https://github.com/mokeyish/smartdns-rs/issues/161#issue-1840512299
nslookup的问题之前提过issue但关闭了，现在也还没解决，不过wireshark抓包可以看到来自不同dns的解析结果。

**Comment by mokeyish** [comment]
我无法重现这个问题，得你自己看了。貌似就你有这问题。怀疑是你自己设置的问题。

**Comment by zbc258** [comment]
> 我无法重现这个问题，得你自己看了。貌似就你有这问题。怀疑是你自己设置的问题。
嗯嗯，好吧，我自己看一下。之前百度查了一下好像和我用的卡巴斯基有关系，会默认阻拦IPV6请求，但是我卸了卡巴斯基问题依然存在。

**Comment by mokeyish** [comment]
有日志么？我一直在 Mac OS 上用，貌似一直都很稳定。

**Comment by zbc258** [comment]
> 有日志么？我一直在 Mac OS 上用，貌似一直都很稳定。

现在大概是这么两种情况：
1.用着用着，日志显示所有上游服务器都超时了，然后就没网。卸载smartdns服务改回默认dns一段时间后恢复正常。
2.用着用着，smartdns服务崩了，日志里也没有记录，就是整个任务进程直接从任务管理器里面消失了，卸载也报错，重新安装服务或者命令行运行后恢复正常。
