### ISSUE TITLE
windows版本域名配置了-no-cache 没有作用

### ISSUE THREAD

**Issue by gexiaopeng** [mokeyish/smartdns-rs#167]
我的域名是阿里云的，阿里云专门的dns是47.118.199.222。
我修改了域名的ip，通过 nslookup  t.xxxx.com 47.118.199.222每次获取到的都是新的ip。
但通过我本地的smartdns 获取到的还是缓存的Ip（10分钟以后会更新）。同样的配置，在linux环境下是正常获取到最新的ip（没有缓存）
（windows环境下启动smartdns服务的时候把缓存文件smartdns.cache删除了的）
测试结果：
![sm1](https://github.com/mokeyish/smartdns-rs/assets/7857056/9ef3df3a-de2c-4b62-9ba5-fe028fcc4bf9)

配置：
![sm2](https://github.com/mokeyish/smartdns-rs/assets/7857056/8128ee7b-5a41-46eb-8551-cc55500ed146)

服务启动日志：
![sm3](https://github.com/mokeyish/smartdns-rs/assets/7857056/e994dd67-45f1-469e-9856-35293c2077e7)

**Comment by mokeyish** [comment]
把 smartdns.cache 删除了，再启动是没问题的么？
