### ISSUE TITLE
Windows版本 卸载报错，启动报错

### ISSUE THREAD

**Issue by wang93wei** [mokeyish/smartdns-rs#168]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "另一个程序正在使用此文件，进程无法访问。" }', src\main.rs:151:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mokeyish** [comment]
先把服务关了。


https://docs.microfocus.com/SM/9.60/Hybrid/Content/serversetup/tasks/stop_the_server_from_windows_services.htm
