### ISSUE TITLE
Whitelist domains

### ISSUE THREAD

**Issue by eminfedar** [mokeyish/smartdns-rs#172]
Hello, I want to prevent access every website except white list.

I have tried a config like this:
```
address /google.com/-
address /*/#
```
Which I thought blocks every address but google.com. But it didn't work.

How can I create a whitelist of domains and block everything but them? 

**Edit:** It can be something like `server 1.1.1.1` but only for these `...` domains? Other domains like just doesn't exists.

**Comment by mokeyish** [comment]
It's not supported yet, but it looks like it would be fairly simple to implement.

**Comment by mokeyish** [comment]
Now, it's supported.

**Comment by eminfedar** [comment]
> Now, it's supported.

Great! Any usage examples?

**Comment by mokeyish** [comment]
Same as you write above.

https://github.com/mokeyish/smartdns-rs/blob/018c977b18458b6bda4648872063173d520e31f0/src/dns_conf.rs#L2447-L2464

haven't release new version yet, but you can download from here.

https://github.com/mokeyish/smartdns-rs/actions/runs/6682783488
