### ISSUE TITLE
cname记录缺失？

### ISSUE THREAD

**Issue by PikuZheng** [mokeyish/smartdns-rs#199]
根据 RFC1034，除非查询类型为CNAME，DNS服务器在递归查询到CNAME后应将CNAME和A记录合并应答

>CNAME RRs cause special action in DNS software.  When a name server
fails to find a desired RR in the resource set associated with the
domain name, it checks to see if the resource set consists of a CNAME
record with a matching class.  If so, the name server includes the CNAME
record in the response and restarts the query at the domain name
specified in the data field of the CNAME record.  The one exception to
this rule is that queries which match the CNAME type are not restarted.
>
>For example, suppose a name server was processing a query with for USC-
ISIC.ARPA, asking for type A information, and had the following resource
records:
>
>    USC-ISIC.ARPA   IN      CNAME   C.ISI.EDU
>
 >   C.ISI.EDU       IN      A       10.0.0.52
>
>**Both of these RRs would be returned in the response to the type A query,**
>while a type CNAME or * query should return just the CNAME.

抓包发现smartdns-rs的应答中缺失了CNAME记录
![image](https://github.com/mokeyish/smartdns-rs/assets/12579522/3d976ff2-4030-40ee-9bfb-7a790d3c2987)

虽然这样做可以避免一些问题，但这不规范。

**Comment by PikuZheng** [comment]
隔壁的服务器，应答中有CNAME记录--->
![image](https://github.com/mokeyish/smartdns-rs/assets/12579522/64b9dc68-a555-47c7-b928-54c5b6ffaf48)

**Comment by PikuZheng** [comment]
> 亲，你的docker有这个库容器？
> 我要上你的库

没有啊 晚点时候我写一个

**Comment by PikuZheng** [comment]
问下 要什么架构的 @Potterli20

**Comment by PikuZheng** [comment]
哪有通用架构啊 🤣

**Comment by PikuZheng** [comment]
> x86😂

```
# file smartdns
smartdns: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
```
对应goarch是`386`，所以`pikuzheng/smartdns-rs:latest-i386`应该是你需要的

**Comment by PikuZheng** [comment]
> 64位的😂
> x86我习惯叫了

```
localhost:~# file /userdata/smartdns/smartdns-rs
/userdata/smartdns/smartdns-rs: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped
```
基本搞定多架构镜像了，`pikuzheng/smartdns-rs:latest` 应该可以自动选择合适的架构

**Comment by PikuZheng** [comment]
> 你能不能fork的项目能不能开通那个iss😂😂

开了，我又不懂代码，开那个干啥:rofl

**Comment by mokeyish** [comment]
#219 修复了，你再验证看看。
