### ISSUE TITLE
使用容器好像异常高

### ISSUE THREAD

**Issue by Potterli20** [mokeyish/smartdns-rs#217]
容器是用@PikuZheng 他的容器
我自己的配置是看图![Screenshot_2023-12-26-08-26-03-296_com.termux.jpg](https://github.com/mokeyish/smartdns-rs/assets/28734349/23e2b2da-905e-47b0-b421-0550ea8e7bd7)

但是一用占用了8个g，感觉有点像内存泄露

**Comment by mokeyish** [comment]
个人在 macos 上用，内存占用 37M 多点。

能泄露的地方感觉是你配置一堆上游服务器，不一定都是响应快的，超时不响应，这样异步任务就堆积越来越多。

缓存应该不会，你可以访问接口 https://localhost/api/caches 看看有多少缓存。https 证书，项目根目录有，你设置信任即可。


我自己一般不会跟你这样用这么多上游服务器的，太多反而速度慢。一个分组最多两个当备用，一个挂了另一个还能正常。

**Comment by PikuZheng** [comment]
![image](https://github.com/mokeyish/smartdns-rs/assets/12579522/29624c6a-e43c-456a-8442-3a8f020662b2)
内存115M

建议关掉debug日志。上游的话建议再梳理一次，像是tls 1.12.12.12和dot.pub就完全是重复的

**Comment by PikuZheng** [comment]
另外问下主机是几个核心几个线程

**Comment by PikuZheng** [comment]
8个G怎么来得，，统计口径问题吧？我用 `docker stats` 显示用掉147.5M内存，但进容器内用free看，显示用掉1.9G内存

**Comment by PikuZheng** [comment]
rust不太可能有内存泄露问题，但似乎内存一直在缓慢增长，没有释放@mokeyish

**Comment by PikuZheng** [comment]
这个是运行了7个小时，内存耗用5G吗？我这观察了45分钟，内存的确一直在增长

**Comment by PikuZheng** [comment]
![image](https://github.com/mokeyish/smartdns-rs/assets/12579522/5e1282a6-3c05-4e28-9ae3-9ead468ace00)
观察了 4小时，从开始运行一小时内，内存耗用一直在增长，然后突然被回收，稳定在182MB左右。虽然仍在缓慢增长，但就目前的斜率来看每小时增加1M的样子。

![image](https://github.com/mokeyish/smartdns-rs/assets/12579522/36668c5f-26ca-49aa-b537-5a92eaf5e52d)
从虚拟机主机统计来看，所有容器内存加上容器自身所在的操作系统的内存合计没有显著增加

**Comment by mokeyish** [comment]
> > 8个G怎么来得，，统计口径问题吧？我用 `docker stats` 显示用掉147.5M内存，但进容器内用free看，显示用掉1.9G内存
> 
> ![Screenshot_2023-12-26-14-37-41-368_com.termux.jpg](https://private-user-images.githubusercontent.com/28734349/292818690-99c00d1a-f8df-41c0-9f38-f39fce516a7b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODY3NjQsIm5iZiI6MTcwMzU4NjQ2NCwicGF0aCI6Ii8yODczNDM0OS8yOTI4MTg2OTAtOTljMDBkMWEtZjhkZi00MWMwLTlmMzgtZjM5ZmNlNTE2YTdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEwMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNWI1MzcxNDUyOGZhYTgzMjc3NTZhNTRhYTYwOWUxODM3MmM3N2IzZjlhZmQ3ZjA1YmY4NDhjNzhmZjQwOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ps3rMR5JqI7V9beX7lbhAkWMVPeiY91bZSd_qoPjUSQ)
> 
> 有时8g，有时5g

这是什么工具

**Comment by mokeyish** [comment]
缓存回收是根据 ttl 的，如果没到最大 size，定时检查，过期太久，就清理了。

**Comment by PikuZheng** [comment]
> 这是什么工具

pve自带面板吧

**Comment by mokeyish** [comment]
把截图放到 google 搜索，找到了，叫 btop。

我这在路由器上运行一天了，稳定在 80M 左右。
![image](https://github.com/mokeyish/smartdns-rs/assets/16131917/f9369d4b-b04d-401c-92e0-bbf478fdf9eb)

---

这是另外一台服务器的，没加域名列表，占用内存比较少 10M 左右。用 dnsperf 压测了下，能升到 100 M，停了，又降回这个水平了。

![image](https://github.com/mokeyish/smartdns-rs/assets/16131917/3efbf0f7-384f-4d2e-8d26-e3894be9a131)

**Comment by PikuZheng** [comment]
> 把截图放到 google 搜索，找到了，叫 btop。

我这出问题了，貌似现在只有缓存工作，没法向上游查询和应答了

**Comment by mokeyish** [comment]
我怀疑是加了太多上游服务器，而这些服务器有些很慢，或者不响应。。。。每个请求都是 Future，响应很慢，新的请求又不断开启，就会堆积。

目前没有加超时，自动屏蔽速度慢，无响应的服务器功能。

**Comment by mokeyish** [comment]
现在这个版本可以通过 ECH 测试了，隐私更有保障了。

https://defo.ie/ech-check.php

![image](https://github.com/mokeyish/smartdns-rs/assets/16131917/7ec09064-bcbc-4c23-a239-08301279f29a)


https://www.cloudflare.com/zh-cn/ssl/encrypted-sni/#results

![image](https://github.com/mokeyish/smartdns-rs/assets/16131917/d7be1c74-1f9e-4000-9aa5-03b10c97ebd5)

**Comment by mokeyish** [comment]
dnssec #195 用 delv 验证的，程序会转发 dnssec 的内容，没有计算验证，这个关系不大。

https://github.com/mokeyish/smartdns-rs/blob/main/src/api/serve_dns.rs#L182 要 ad 为 true，这直接写死都成。

**Comment by mokeyish** [comment]
我上面都怀疑了那么多次了，你都不帮忙验证一下，排查到具体原因的点？不确定原因，一般不会随便改

**Comment by PikuZheng** [comment]
可以看一下网络连接数和内存用量是不是正相关？

**Comment by mokeyish** [comment]
建议先把每个 group 的服务器缩减到两个最快的（两个内容一样，其实是起到备份的作用，防止一个挂了，这是是为什么各大系统默认就是两个）。这些返回的内容基本一样，没啥用。

搞这么多一个是会影响性能，另一个就卡慢的服务器，对它发起的请求会占用内存。


你想吧每秒接收1000个请求，但是卡慢的服务器5秒返回，或者直接不返回，这不就越堆越多，内存占用高了，CPU 计算能力是一定的，这也会导致正常的查询变慢。。

**Comment by mokeyish** [comment]
把我怀疑证实了，降低上游服务器，确实可以解决问题。那么就是我猜想的原因，后续安排增加对卡慢的服务器进行自动禁用。

**Comment by mokeyish** [comment]
总要确定原因吧，解决问题。。。。我自己用连续三天稳定 80M 左右，没有任何问题。

**Comment by PikuZheng** [comment]
> 其实想不限制的请求，不影响多个dns请求就行，我的cpu才j4125。但我的用户那边请求多，所以会boom的。
> mosdns那边最多能请求3个，而smartdns和dnsproxy都不限制，但是dnsproxy用了分流文件会占用3个g不变，而smartdns这样的分流文件，才占用20m😂

这个思路是不对的，smartdns是并发式向上游查询，同时获得多个上游结果，然后按规则丢弃不需要的。那么比如30个上游查询一个域名，就会产生60次并发（A+AAAA），假设合并结果后有5个ip，还会产生5次测速。这样算的话，100个用户每个用户连续查10个域名，并发连接数就满了。
然而同时向30个上游发起查询是没有必要的，因为重复的上游（单一供应商，包括http和tls）给出的结果在大多情况下都是一样的，反复查询除了增加流量，不会增加什么优势。
考虑到dot首次连接快，doh（建立连接后）二次查询快，我建议每个供应商保留一个dot或doh，总数量在4到6个即可。

**Comment by PikuZheng** [comment]
> 那我等作者开发开类似adgh [https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains这种格式](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains%E8%BF%99%E7%A7%8D%E6%A0%BC%E5%BC%8F)
> 我有脚本写这种dns文件

所以你的需求其实是不同域名对应不同上游，但对应得很细化是吗？这种情况下用上游组也不是不能配置，但很麻烦

**Comment by PikuZheng** [comment]
根据我这两天观察，内存耗用和规则数量、缓存数量正相关，且程序在（没有客户发起查询）空闲时会回收内存。另外rust语言不太可能有内存泄露。
感觉问题可能还是出在大并发连接，看看是不是pve限制了并发数（debian的pam_limits？）导致了连接排队什么的

**Comment by PikuZheng** [comment]
> podman run -d --name smartdns --restart=always --label io.containers.autoupdate=registry --net=host -v /mnt/pve/potter1/file/dns/smartdns:/etc/smartdns docker.mirrors.sjtug.sjtu.edu.cn/pikuzheng/smartdns-rs:latest

建议换成lxc试试
