### ISSUE TITLE
Windows下路径识别问题

### ISSUE THREAD

**Issue by TnZzZHlp** [mokeyish/smartdns-rs#220]
无法识别 `C:\Users\Administrator\Desktop\smartdns\smartdns.log` 这种写法 这样写会报错

> 2023-12-30 20:43:00.386:WARN:smartdns::dns_conf::parse:806: unknown conf: cache-file, Error(Error { input: "cache-file C:\\Users\\Administrator\\Desktop\\smartdns\\smartdns.cache", code: Tag })

修改为 `C:\\Users\\Administrator\\Desktop\\smartdns\\smartdns.log` 这种写法后可以正常识别

**Comment by mokeyish** [comment]
#223 已经修复了
