### ISSUE TITLE
能否做这个进阶玩法（dot/doq）

### ISSUE THREAD

**Issue by Potterli20** [mokeyish/smartdns-rs#222]
如这个 https://kbsml.com/?p=515
目前我用nginx 做了dot，但doq不行

**Comment by TnZzZHlp** [comment]
可能是不支持udp导致的？
可以看看这篇文章 [](https://www.nginx.org.cn/article/detail/76)

**Comment by mokeyish** [comment]
个人推荐用 DoH 和 DoH3。

DoT 和 DoQ 有专属端口，特征明显，有些 ISP 或者一些提供 WIFI 门店会屏蔽的，逼迫你使用非加密的 53 端口，以便于收集隐私信息，做广告投放等恶意行为。
