### ISSUE TITLE
If max-reply-ip-num is set to 1, an empty record will be returned if the CNAME record is set for the domain name.

### ISSUE THREAD

**Issue by TnZzZHlp** [mokeyish/smartdns-rs#225]
![image](https://github.com/mokeyish/smartdns-rs/assets/98214647/5d75832e-30af-4953-99c4-d5862459612e)

**Comment by mokeyish** [comment]
Why did you close this issue?

**Comment by TnZzZHlp** [comment]
> Why did you close this issue?

It seems my config is wrong, I'm going to test more to check it out.
I'll reopen this issue when I'm ready.
