### ISSUE TITLE
0.7.1 版本，在win7_32位系统，提示，与您运行的windows版本不兼容，无法运行。

### ISSUE THREAD

**Issue by anszyeah** [mokeyish/smartdns-rs#227]
0.7.1 版本，在win7_32位系统，提示，与您运行的windows版本不兼容，无法运行。

**Comment by mokeyish** [comment]
已增加，windows-32 位版本 https://github.com/mokeyish/smartdns-rs/releases/download/0.7.2/smartdns-i686-pc-windows-msvc.zip
