### ISSUE TITLE
[Bug Report] 域名预先获取功能逻辑问题

### ISSUE THREAD

**Issue by TnZzZHlp** [mokeyish/smartdns-rs#235]
在开启域名预先获取功能的情况下，如果有多个分组应该用第一次查询的分组来进行后续的域名预先获取。
但是我看下了日志好像所有域名都默认使用Default分组进行获取了，求大佬解答

![image](https://github.com/mokeyish/smartdns-rs/assets/98214647/f5782dde-e3b1-4a4d-b139-d587a994a1d1)

**Comment by mokeyish** [comment]
预读取属于后台查询，日志不是那么多。不过复制了一开始的查询选项的，分组应该是一致的。

初始化默认分组跟查询是不是用这个分组没关系的。

**Comment by mokeyish** [comment]
你可以多开1个 dns 服务作为其中一个分组上游看看，查询之后，把查询域名 ip 地址改了重启，看预读取是不是按配置的分组查询的。

**Comment by mokeyish** [comment]
你这种配置，一个域名查询可能从53进，也可能从54进？两者的查询不一样，54 进的话不走自动判断分组了。这样预读取只能复制其中一个查询选项，谁先用谁。

**Comment by mokeyish** [comment]
> 没懂 **自动判断分组** 这里是什么意思
> 
> 按正常逻辑来说不应该像下图所示的么 ![image](https://private-user-images.githubusercontent.com/98214647/302105137-eb07f20b-b7b8-41a6-9cba-f672e54543c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTY1MDUsIm5iZiI6MTcwNzA1NjIwNSwicGF0aCI6Ii85ODIxNDY0Ny8zMDIxMDUxMzctZWIwN2YyMGItYjdiOC00MWE2LTljYmEtZjY3MmU1NDU0M2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE0MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0Yzc3ZThjZWJiOTM4NjYxZmIzMzcyMWJmNmQxZDk1ZmRlMDczYzNjYzBkNDNkMWI2NzM2MzcxNzhlNTk5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PappFPF02Fm0XNoXpzx1Gaz045RWK9IGBLV9YfrVEls)
> 
> 我的配置是域名分流在进smartdns前就做好，然后查询不同的dns分组

嗯，你这解释的不错，后面改成这种实现。

现在这个版本缓存没有记录由哪个组查询到的。直接就是根据域名和查询类型，所以 53 进就是默认分组，54 进就是ts分组，然后就串了

**Comment by mokeyish** [comment]
临时解决办法就是，在54 bind 那加个禁用缓存选项。
