### ISSUE TITLE
domain-set 似乎没有正常工作

### ISSUE THREAD

**Issue by Elypha** [mokeyish/smartdns-rs#24]
```
aaa.com
abab.com
```
```
domain-set -name block -file E:/apps/smartdns/block.txt
address /domain-set:block/#
```
这样写入后似乎没有生效（如果没写错的话
表现为配置为 `#` 的域名还可以正常解析
而把文件格式化成
```
address /aaa.com/#
```
再通过 conf-file 方式引入是可以的（表现为解析出SOA

Version:
https://github.com/mokeyish/smartdns-rs/releases/tag/0.1.6

OS:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎24/‎11/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

Device:
Processor	AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by mokeyish** [comment]
好像配置文件，实现的是 –f 而不是 file

**Comment by Elypha** [comment]
测试了一下，`-f` 似乎也不行
但是启动的时候没任何报错，即使文件路径写错了也没报错（如果不是预期行为的话

**Comment by mokeyish** [comment]
> 测试了一下，`-f` 似乎也不行 但是启动的时候没任何报错，即使文件路径写错了也没报错（如果不是预期行为的话

-name 也是 -n 缩写的。

**Comment by mokeyish** [comment]
@Elypha 在 #25 上修复了，等打包完成版本:[0.1.7](https://github.com/mokeyish/smartdns-rs/releases/tag/0.1.7)，你再验证看看，是否解决了。
