### ISSUE TITLE
service install安装成服务能否指定conf文件？

### ISSUE THREAD

**Issue by xsd871** [mokeyish/smartdns-rs#240]
service install安装成服务能否指定conf文件？目前发现安装之后是重新生成的配置，不是读取文件夹下的配置 需要重新编辑一下

**Comment by mokeyish** [comment]
默认不会覆盖配置的。而且加个 default 后缀。

https://github.com/mokeyish/smartdns-rs/blob/458a80c029f62c9bdd78b23f9f4cd949e66f473e/src/service/installer.rs#L390
