### ISSUE TITLE
geosite 的支持

### ISSUE THREAD

**Issue by onion83** [mokeyish/smartdns-rs#246]
v2ray 的衍生项目 geosite 已经有了大量的用户基础和成熟的更新机制，可以解决自己写脚本东拼西凑的更新麻烦，smartdns 作者明确表示不支持特定数据 https://github.com/pymumu/smartdns/issues/1274 ,作为差异化发展的 smartdns-rs 希望考虑支持一下，谢谢。

**Comment by mokeyish** [comment]
这边也不打算支持特定格式。这个软件的场景主要是家用或者企业内部的私有域名解析，以及通过加密 DNS 的隐私保护，还有就是缓存加速之用。
