### ISSUE TITLE
请求增加mdns-lookup功能

### ISSUE THREAD

**Issue by blog2i2j** [mokeyish/smartdns-rs#252]
感谢大神开发win下的smartdns. 我发现不能使用mdns-lookup参数(原作者的里面有这个参数), 请问是不是不支持? 请求增加mdns-lookup用于主机名解析.

**Comment by mokeyish** [comment]
有个bug未解决，暂时没有上。

**Comment by blog2i2j** [comment]
明白，感谢大神让我用上了win下的smartdns

**Comment by mokeyish** [comment]
#545
