### ISSUE TITLE
What is the difference between GNU and MSVC?

### ISSUE THREAD

**Issue by geraistec** [mokeyish/smartdns-rs#293]
What is the difference between GNU and MSVC?

**Comment by mokeyish** [comment]
In Rust on Windows, GNU and MSVC refer to different sets of tools and libraries used for compilation.

GNU refers to the GNU toolchain, which includes the GNU Compiler Collection (GCC) and associated tools. It's typically used on Unix-like systems but can be used on Windows with tools like MinGW or MinGW-w64.

MSVC refers to the Microsoft Visual C++ compiler toolchain provided by Microsoft, commonly used on Windows systems.

In Rust, you can choose between these toolchains for compiling your code on Windows. Each has its own set of features, compatibility, and performance characteristics.
