### ISSUE TITLE
设置成非53端口不能生效

### ISSUE THREAD

**Issue by jelly0930** [mokeyish/smartdns-rs#294]
53端口容易被占用，我就修改bind端口未853，但似乎没有效果，是还需要做其它步骤吗

![image](https://github.com/mokeyish/smartdns-rs/assets/37065209/4cdd34be-875e-4fba-8e23-c9728fc6c758)

**Comment by mokeyish** [comment]
看不出什么问题，任意端口都可以设置。但查询的命令，也要跟着改成对应端口。

**Comment by tangkunyin** [comment]
mac m1机器，通过brew安装，运行：`sudo smartdns -q run` 提醒53端口被占用

@mokeyish 请问，如果53端口改了，你后边说的查询命令也要跟着改，改怎么操作呢？

**Comment by mokeyish** [comment]
建议关闭原来 53 占用的程序。

命令行上，dig -p 可以指定端口。但其他程序可不认这个，还是用默认的端口的。

具体可以谷歌一下。
