### ISSUE TITLE
cpu占用异常

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#295]
0.8.2版本，服务模式运行一小时以上，cpu占用开始飙升，重启服务后恢复正常，再等一小时左右问题再次出现：
![image](https://github.com/mokeyish/smartdns-rs/assets/91818523/71b00ed5-c7f2-4ded-bbbe-32a33cca8eb5)

**Comment by mokeyish** [comment]
是不是开了，域名预读取？

**Comment by zbc258** [comment]
> 是不是开了，域名预读取？

还真是，这东西这么吃cpu的吗？以前版本我也开着，这次更新完没改配置就直接安装了。

**Comment by mokeyish** [comment]
你可以自行编译，调高这个值。

https://github.com/mokeyish/smartdns-rs/blob/aa17d0fe958a3678f510f1e136b2c1636602d7af/src/dns_mw_cache.rs#L145

**Comment by mokeyish** [comment]
https://github.com/mokeyish/smartdns-rs/actions/runs/9427011136

你下载这个版本试试，我怀疑是你用的部分域名查询加测速慢，之前版本没有标记，重复发起相同域名的查询。所以往检查域名过期加了标记，如果正在查询就不再发起新的查询了。

另外还是如此，就配置环境变量PREFETCH_MIN_INTERVAL 单位是秒。增加最下检查的时间间隔。
