### ISSUE TITLE
win10不能用吗？

### ISSUE THREAD

**Issue by chinaniupai** [mokeyish/smartdns-rs#296]
打不开exe

**Comment by mokeyish** [comment]
这让我怎么解答？打不开exe，这不大可能，你是双击打开了？这是命令行后台服务程序，没有界面，要安装成服务。

如果你以为是有界面的，这个程序不适合你使用，因为配置太复杂了，要自己研究看文档。

配置文档在
https://pymumu.github.io/smartdns/configuration/
