### ISSUE TITLE
windows 版本卸载服务报错

### ISSUE THREAD

**Issue by jelly0930** [mokeyish/smartdns-rs#297]
smartdns 版本0.7.2

我在卸载时也遇到了错误，
smartdns service uninstall
2024-06-06 14:45:47.585:ERROR:smartdns::service::service_manager:177: Failed
thread 'main' panicked at src\main.rs:148:18:
called Result::unwrap() on an Err value: Custom { kind: Other, error: "Failed" }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

![image](https://github.com/mokeyish/smartdns-rs/assets/37065209/eb3ef23d-4b03-4358-9e4e-e0f63be64b9c)

然后按提示设置了RUST_BACKTRACE=1,set RUST_BACKTRACE=full 两个环境变量，再次卸载时又遇到了新的报错，问下这个怎么处理呢

smartdns service uninstall
2024-06-06 15:03:06.239:ERROR:smartdns::service::service_manager:177: Failed
thread 'main' panicked at src\main.rs:148:18:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed" }
stack backtrace:
   0:     0x7ff75990b323 - <unknown>
   1:     0x7ff75952459d - <unknown>
   2:     0x7ff7598d5d3d - <unknown>
   3:     0x7ff75990ce33 - <unknown>
   4:     0x7ff75990c78f - <unknown>
   5:     0x7ff75990d270 - <unknown>
   6:     0x7ff75990d05e - <unknown>
   7:     0x7ff75990cfa9 - <unknown>
   8:     0x7ff75990cf94 - <unknown>
   9:     0x7ff759522fe7 - <unknown>
  10:     0x7ff759528773 - <unknown>
  11:     0x7ff759898485 - <unknown>
  12:     0x7ff7598a5aa1 - <unknown>
  13:     0x7ff7598a1a93 - <unknown>
  14:     0x7ff75989abc6 - <unknown>
  15:     0x7ff75989aae6 - <unknown>
  16:     0x7ff75989a8a6 - <unknown>
  17:     0x7ff7594c12ef - <unknown>
  18:     0x7ff7594c1406 - <unknown>
  19:     0x7fffd1fb257d - <unknown>
  20:     0x7fffd286aa48 - <unknown>

![image](https://github.com/mokeyish/smartdns-rs/assets/37065209/41975fb7-3f84-43b9-9cd6-256bfee02c00)

**Comment by mokeyish** [comment]
修复了，测试了几种情况。你可以再试试，如果有问题再说详细重现步骤。
