### ISSUE TITLE
expand-ptr-from-address选项无效

### ISSUE THREAD

**Issue by haiger01** [mokeyish/smartdns-rs#308]
expand-ptr-from-address选项无效，什么时候支持呀？

**Comment by mokeyish** [comment]
这个参数什么意思？原理是啥？

**Comment by haiger01** [comment]
例如生成一个自定义DNS配置文件dns.hosts包含在配置选项hosts-file /etc/smartdns/hosts/dns.hosts里面，配置文件内容为
root@devdb:~/dns/smartdns# cat hosts/dns.hosts 
1.1.1.1 aa.aa
2.2.2.2 bb.bb

配置expand-ptr-from-address yes后
正常dig aa.aa @127.0.0.1 解析为1.1.1.1   dig -x 1.1.1.1 @127.0.0.1 解析出来的域名应该为aa.aa

目前配置expand-ptr-from-address yes后
dig aa.aa正常，dig -x 1.1.1.1异常，自定义域名解析及IP反向解析应该高于外部解析

**Comment by mokeyish** [comment]
好的，等这个 PR 被上游合并，就加上来。

https://github.com/mokeyish/hickory-dns/tree/ptr

**Comment by haiger01** [comment]
非常感谢！

**Comment by haiger01** [comment]
#hosts-file /etc/smartdns/hosts/*
hosts-file /etc/smartdns/hosts/dns.hosts
另外如上所示，配置文件选项里面能否支持通配符加载多个配置文件呀，多个配置文件多行加载不是很友好

**Comment by mokeyish** [comment]
已经支持 https://github.com/mokeyish/smartdns-rs/pull/335 。 打包的版本在这：https://github.com/mokeyish/smartdns-rs/actions/runs/10015510298

**Comment by haiger01** [comment]
已测试，感谢！
