### ISSUE TITLE
偶尔解析失败

### ISSUE THREAD

**Issue by JianleiZhang** [mokeyish/smartdns-rs#319]
默认配置，就添加了有一个server。日志报错如下：
```
thread 'smartdns-runtime' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select_ok.rs:38:5:
iterator provided to select_ok was empty
```

**Comment by mokeyish** [comment]
全局搜索，就这个一个地方用了 select_ok 应该可能是没有查询 ip，

**Comment by mokeyish** [comment]
https://github.com/mokeyish/smartdns-rs/blob/2813df79541e29f358ae68b190faea3f8eb34949/src/infra/ping.rs#L50

**Comment by JianleiZhang** [comment]
需要我再提供哪些资料，方便继续排查吗？

**Comment by mokeyish** [comment]
这个是 panic 问题，我直接加个检查修复一下。

**Comment by mokeyish** [comment]
这里修复了 https://github.com/mokeyish/smartdns-rs/pull/321

到这里下载编译好的程序验证看看：

https://github.com/mokeyish/smartdns-rs/actions/runs/9621814056

**Comment by JianleiZhang** [comment]
用了一会儿，好像没报错了。
