### ISSUE TITLE
请问Windows版本安装之后, 配置文件在哪里?

### ISSUE THREAD

**Issue by os9sur** [mokeyish/smartdns-rs#32]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/6024166/218236979-53e7961c-694c-4116-8eec-1f65fc5f8b48.png">

**Comment by mokeyish** [comment]
参考这里：https://github.com/mokeyish/smartdns-rs#windows

文件在这里：

https://github.com/mokeyish/smartdns-rs/blob/dcee2cd99f1c302bba61728bfa475af561629153/src/service/windows/mod.rs#L17-L37

**Comment by os9sur** [comment]
> 参考这里：https://github.com/mokeyish/smartdns-rs#windows 要安装成服务，才可以自动开启启动，不安装服务直接调 run 子命令就好了。
> 
> 安装服务的文件在这里：
> 
> https://github.com/mokeyish/smartdns-rs/blob/dcee2cd99f1c302bba61728bfa475af561629153/src/service/windows/mod.rs#L17-L31

我知道, 我已经安装成服务了, 接下来不是还有 配置文件嘛? 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/6024166/218237963-69c56864-c905-4d82-a605-fccec40b564c.png">

**Comment by os9sur** [comment]
> 好的谢谢!
