### ISSUE TITLE
守护进程的控制接口 Control API of daemon

### ISSUE THREAD

**Issue by cathay4t** [mokeyish/smartdns-rs#327]
请问是否有计划支持守护进程的控制接口，方便外部软件（如NetworkManager）将DHCP获取的DNS 服务器添加到守护进程的配置中。

作为参考:
 * unbound 使用tcp 端口8953 ，配合TLS做认证。
 * systemd-resolved使用D-BUS.
 * dnsmasq: 无控制API

我可以做个unix file socket 的demo.

Do we have any plan on add control API to the daemon in the seek of allowing external tool(e.g. NetworkManager) appending DNS nameserver retrieved from DHCP to SmartDNS-rs daemon?

As reference:
 * unbound uses TCP 8953 port with TLS authentication.
 * systemd-resolved uses D-BUS.
 * dnsmasq: no control API

I may create a demo using unix file socket.

**Comment by mokeyish** [comment]
自动更新 DHCP 的 DNS 服务器是某些场景必要的，但我对这个 NetworkManager 通知的协议不了解（还是任何接口都可以，只是触发刷新？）。

**Comment by cathay4t** [comment]
什么接口都可以。
如你没什么偏好，我就做个demo PR我们再讨论。

**Comment by mokeyish** [comment]
我倾向于使用 unix file socket ，这样可以用 http，不用 https 加密。然后处理代码定义在这里。

https://github.com/mokeyish/smartdns-rs/blob/main/src/api/nameserver.rs

目前是开启了 https 的 DoH 监听，才会启用这些http api 接口。

**Comment by cathay4t** [comment]
@mokeyish 抱歉，我们决定使用其他项目: https://github.com/InfrastructureServices/dnsconfd
