### ISSUE TITLE
domain-set 不生效

### ISSUE THREAD

**Issue by PhoenixTrees** [mokeyish/smartdns-rs#332]
配置如下

**Comment by PhoenixTrees** [comment]
server-name smartdns

speed-check-mode ping,tcp:80,tcp:443

bind 127.0.0.1:53 -force-aaaa-soa 

cache-size 32768
cache-persist yes
cache-file D:\data\cache\smartdns\smartdns.cache

force-qtype-SOA 65

dualstack-ip-selection no

log-level debug
log-file D:\data\log\smartdns\smartdns.log
log-size 10240k

server 223.5.5.5 -bootstrap-dns -exclude-default-group

server-https https://doh.pub/dns-query  -group domestic 
server 114.114.114.114  -group domestic 
server-https https://dns.alidns.com/dns-query  -group domestic 
server 180.76.76.76  -group domestic 
server 202.96.209.133  -group domestic 
server 116.228.111.118  -group domestic 
server 210.22.70.3  -group domestic 
server-tls dot.360.cn  -group domestic 
server 1.2.4.8  -group domestic 
server-https https://dns.twnic.tw/dns-query  -group domestic 
server 210.22.84.3  -group domestic 

#oversea
server-https https://dns.google/dns-query  -group oversea -exclude-default-group 
server-https https://cloudflare-dns.com/dns-query  -group oversea -exclude-default-group 
server-https https://dns.quad9.net/dns-query  -group oversea -exclude-default-group 
server-https https://public.dns.iij.jp/dns-query  -group oversea -exclude-default-group 

# lan
server 10.1.1.254

domain-set -n proxy -f C:\Users\kehuduan\Document\proxy.domin
domain-rules /domain-set:proxy/ -nameserver oversea -speed-check-mode none

**Comment by PhoenixTrees** [comment]
[Uploading proxy.txt…]()

**Comment by PhoenixTrees** [comment]
[proxy.txt](https://github.com/user-attachments/files/16140827/proxy.txt)
![image](https://github.com/mokeyish/smartdns-rs/assets/48588697/146b686c-71d1-4dad-bb7b-c5b0d21e3639)
[log.txt](https://github.com/user-attachments/files/16140863/log.txt)

**Comment by PhoenixTrees** [comment]
是我哪里配置出问题了吗？我从openwrt上面的配置抄过来的，顺便可以再日志里面加一下生效的domain-set和domain-rules，方便排查问题吗？

**Comment by mokeyish** [comment]
你在 linux 上试过吗？看着好像是 windows 路径解析的问题？

我用 windows 比较少。更多是用 MacOS 和 Linux。

**Comment by PhoenixTrees** [comment]
> 你在 linux 上试过吗？看着好像是 windows 路径解析的问题？
> 
> 我用 windows 比较少。更多是用 MacOS 和 Linux。

 没有只在windows用过，而且我翻了翻之前的issue，发现您的回复说 -h + url 也支持，我也试了下，没有成功 不知道是哪里的问题

**Comment by mokeyish** [comment]
![image](https://github.com/user-attachments/assets/08fa0b4a-cade-4ed6-98f3-a9284f80cb3b)


无法重现

**Comment by PhoenixTrees** [comment]
> ![image](https://private-user-images.githubusercontent.com/16131917/348287556-08fa0b4a-cade-4ed6-98f3-a9284f80cb3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTQ5ODAsIm5iZiI6MTcyMDc5NDY4MCwicGF0aCI6Ii8xNjEzMTkxNy8zNDgyODc1NTYtMDhmYTBiNGEtY2FkZS00ZWQ2LTk4ZjMtYTkyODRmODBjYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0MzEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NjU0Yzg4ODQ5MmVkZmZiOWRkMDI4MjE5NDg2MGQ4ZDIxYjg4NDAzODM0NjBmNTMxZjFlYTc5YTBiZTQyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FI75lGWbprfz59OrBSck4eT6PWTsmTSeil9xRYoFU1A)
> 
> 无法重现

我把文件放到d盘也好了， 可能是我之前放的路径有问题？ 感谢回复
