### ISSUE TITLE
想问下是否支持 ECS

### ISSUE THREAD

**Issue by Skyxim** [mokeyish/smartdns-rs#35]
没看到说明里有说是否支持，trust-dns 好像也不支持。所以有个疑问，最近在找 AdGuardHome 服务器上的替代品

**Comment by mokeyish** [comment]
ECS 是云服务器？这个 linux amd64 那个版本不行吗？release 那里可以下载。adguardhome 我也用过，不过它好像不支持 DOH 加密分流。trust-dns 定位是对标 bind 的，这个库也是依赖它的协议层的，定位还是个人家庭局域网使用的。

**Comment by Skyxim** [comment]
EDNS Client Subnet 这个，转发给上级服务器子网

**Comment by mokeyish** [comment]
这个啊，还没深入了解， edns 协议层有，但我没用它，先把常用功能覆盖全了，再去开发这个😂

**Comment by mokeyish** [comment]
@mokeyish 已经支持 ECS 了。 https://github.com/mokeyish/smartdns-rs/pull/87

这种比较难测试，一般成功，一般失败。。，

![图片](https://user-images.githubusercontent.com/16131917/227700534-b0969f9d-3f03-4e2b-9c7d-3b66afbe1844.png)

你有啥好的域名和子网能方便做这种测试的么？我用 CDN 域名，服务器可能会返回一样的 IP，导致测试失败。

![图片](https://user-images.githubusercontent.com/16131917/227700601-071a7695-c9a7-466b-9e26-e6a2cc208978.png)

**Comment by mokeyish** [comment]
@Skyxim  已经支持 ECS 了。 https://github.com/mokeyish/smartdns-rs/pull/87
