### ISSUE TITLE
添加dns后出现错误

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#36]
在配置文件添加多个dns sever后，出现错误提示：
1676815550:WARN:smartdns::trust_dns:33: nameserver 101.101.101.101:53 skipped. Timeout
1676815583:ERROR:smartdns::dns_server:212: error sending response: unknown

**Comment by mokeyish** [comment]
它使用 ping 过滤了不可用的服务器，防止它不停的查询不可用的服务器，忽略这个，不是错误，正常的。有一点 linux 下，ping 需要 root 账号，windows 和 macos 应该是不要特殊权限。

**Comment by zbc258** [comment]
> 

感谢您的解答，然而软件正常运行的时候（命令行除了这个没有任何别的提示 ，服务正常挂在后台），也顺利监听了127.0.0.1:53端口（使用命令检测可以显示smartdns）后电脑无法访问任何网站，显示找不到ip地址，停止smartdns并恢复本机dns后可以正常上网。

**Comment by mokeyish** [comment]
你的服务器 ping 都关了么，过滤完了没服务器了？我之前想的是，公共 dns 服务器都是开了 ping 的。

你可以 `smartdns run -c <conf-file> -d` 来跑在前台， `-d` 会显示 debug 信息的。

你可以先注释掉，这几个行，然后自己构建一个新包看看。
https://github.com/mokeyish/smartdns-rs/blob/22be0a8565c6405b77fd9cabe9c8ef924cbc21a5/src/dns_client.rs#L428-L431

昨天在重写 dns_client，性能有提升，但是没完全写好，不能提交。

**Comment by zbc258** [comment]
> 你的服务器 ping 都关了么，过滤完了没服务器了？我之前想的是，公共 dns 服务器都是开了 ping 的。
> 
> 你可以 `smartdns run -c <conf-file> -d` 来跑在前台， `-d` 会显示 debug 信息的。
> 
> 你可以先注释掉，这几个行，然后自己构建一个新包看看。
> 
> https://github.com/mokeyish/smartdns-rs/blob/22be0a8565c6405b77fd9cabe9c8ef924cbc21a5/src/dns_client.rs#L428-L431
> 
> 昨天在重写 dns_client，性能有提升，但是没完全写好，不能提交。
感谢您的回复。
我添加的都是常见的那几个公共dns，1.2.4.8，1.1.1.1，119.29.29.29这些，自己在shell里面直接ping都是通的，但是加到smartdns的config里面再运行就都会提示上面这个，然后就彻底不能上网了，要么两个一起提示，要么只提示下面这句。

**Comment by mokeyish** [comment]
你试试这里的配置 https://github.com/mokeyish/smartdns-rs/tree/main/tests/example 我这边主要用的是 DoH

另外记得刷新一下系统的 dns 缓存。

或者你把完整的配置拿上来我看看。

**Comment by mokeyish** [comment]
![图片](https://user-images.githubusercontent.com/16131917/220006766-bad17377-bac6-4e27-8237-ccb0ac2f81b1.png)
我的 mac 电脑上，这里开启域名预读取后，常用的域名都是 0 毫秒。

**Comment by zbc258** [comment]
> ![图片](https://user-images.githubusercontent.com/16131917/220006766-bad17377-bac6-4e27-8237-ccb0ac2f81b1.png) 我的 mac 电脑上，这里开启域名预读取后，常用的域名都是 0 毫秒。

感谢您的认真解答。
我发现它的解析似乎非常不稳定。
就在刚刚，我没有修改任何配置文件，单纯的重启了一下电脑，再运行smartdns就能正常上网了，命令行里只有WARN:smartdns::trust_dns:33: nameserver 101.101.101.101:53 skipped. Timeout的警告，没有下面那句ERROR。
然后我尝试下载并替换了您所给的所有配置文件，smartdns运行没有任何问题（WARN和ERROR都没有），但依然无法上网，依然是显示找不到ip地址。
以上每次更改前我都会刷新windows的dns缓存。

**Comment by mokeyish** [comment]
建议： 你先自己把 下面代码注释掉，再重新编译一个，单纯靠 ping  也确实不合适，后面我再改成个基于统计观测。
https://github.com/mokeyish/smartdns-rs/blob/22be0a8565c6405b77fd9cabe9c8ef924cbc21a5/src/dns_client.rs#L428-L431

先安装 rust 环境 https://www.rust-lang.org/tools/install 再用下面命令编译
```shell
git clone https://github.com/mokeyish/smartdns-rs.git
cd smartdns-rs

# 编译
cargo build --release

# 查看命令帮助
./target/release/smartdns help

# 运行
sudo ./target/release/smartdns run -c ./etc/smartdns/smartdns.conf
```

**Comment by zbc258** [comment]
> 建议： 你先自己把 下面代码注释掉，再重新编译一个，单纯靠 ping 也确实不合适，后面我再改成个基于统计观测。
> 
> https://github.com/mokeyish/smartdns-rs/blob/22be0a8565c6405b77fd9cabe9c8ef924cbc21a5/src/dns_client.rs#L428-L431
> 
> 先安装 rust 环境 https://www.rust-lang.org/tools/install 再用下面命令编译
> 
> ```shell
> git clone https://github.com/mokeyish/smartdns-rs.git
> cd smartdns-rs
> 
> # 编译
> cargo build --release
> 
> # 查看命令帮助
> ./target/release/smartdns help
> 
> # 运行
> sudo ./target/release/smartdns run -c ./etc/smartdns/smartdns.conf
> ```

问题似乎不是在检测原理上的。
我又反复进行了测试，发现问题出在服务上。同一个配置文件，如果smartdns以服务方式运行，必然导致无法上网。
而如果停止并卸载它的服务，直接用命令行运行，smartdns就运行良好，解析速度明显上升，游戏的网络延迟也降低了。

**Comment by mokeyish** [comment]
说了这么多，你是什么操作系统？版本?

**Comment by zbc258** [comment]
> 说了这么多，你是什么操作系统？版本?

我的系统是win11，专业版，22h2正式版。

**Comment by mokeyish** [comment]
我试了正常的，你可以先监听你电脑 ip 直接写死，如果使用了 wsl 貌似 53 端口会被占用。

加开启日志看看：
```ini
log-level debug

log-file d:/smartdns.log
```

另外我临时改了下，去掉 ping 过滤了: [0.1.10](https://github.com/mokeyish/smartdns-rs/releases/tag/0.1.10)

**Comment by zbc258** [comment]
> 我试了正常的，你可以先监听你电脑 ip 直接写死，如果使用了 wsl 貌似 53 端口会被占用。
> 
> 加开启日志看看：
> 
> ```ini
> log-level debug
> 
> log-file d:/smartdns.log
> ```
> 
> 另外我临时改了下，去掉 ping 过滤了: [0.1.10](https://github.com/mokeyish/smartdns-rs/releases/tag/0.1.10)

哎，感谢您这么耐心帮我解答了，我又试了一下午，不仅拿我自己电脑，也拿师弟的（win11系统）和实验室的旧电脑（win7系统）试过了刚刚发的新版本，都是命令行运行没任何问题，然后服务状态运行，过一会服务自己就停了，任务管理器里面进程还在，但是不解析了，需要手动输restart命令，输完立马又可以运行了。

**Comment by mokeyish** [comment]
看看日志吧，这样也不知道什么问题。

**Comment by zbc258** [comment]
> 看看日志吧，这样也不知道什么问题。我自己的 mac 电脑，用了几个月都没问题。

**Comment by zbc258** [comment]
> 看看日志吧，这样也不知道什么问题。我自己的 mac 电脑，用了几个月都没问题。

日志里面没报任何错误，但我终于知道问题在哪了，我们学校的外网有问题，不管上内外网dns都是同一个静态的域名，而且它似乎有防火墙还是什么东西不允许我更换别的dns服务器，所以解析了一阵子后就会被学校这边阻断，然后清除dns缓存再重启服务就又可以解析了，过一会再次被阻断。
我把学校的那个dns加进config就没事了，不过好像这样一来smartdns也就不起作用了😂

**Comment by mokeyish** [comment]
你是用什么协议被阻断的？

**Comment by zbc258** [comment]
> 你是用什么协议被阻断的？

我端口是默认的53没改，应该就是udp吧，但是很奇怪，我昨天专门借了个ubuntu系统的本子装了原版（就是C语言那个）的smartdns再连校园网，并没有发生这种情况，甚至校园网登录界面也可以正常进去。windows系统上哪怕添加了那个静态的dns也进不去校园网登录界面，所以现在我只能先开机连网再开smartdns😂

**Comment by mokeyish** [comment]
配置文件是?

**Comment by zbc258** [comment]
> 配置文件是?
bind localhost:53

server 202.206.240.12 
server 202.206.240.13
server 1.2.4.8
server 1.1.1.1
server 114.114.114.114
server 114.114.115.115
server 208.67.222.222 
server 208.67.222.220 
server 119.29.29.29
server 182.254.116.116
server 101.101.101.101
server 101.102.103.104
server 119.13.92.87

server-https https://223.5.5.5/dns-query  
server-https https://223.6.6.6/dns-query 
server-https https://doh.pub/dns-query  
server-https https://dns.alidns.com/dns-query
server-https https://dns.google/dns-query
server-https https://dns.cloudflare.com/dns-query 
server-https https://dns.quad9.net/dns-query
其余部分均与安装后默认的文件一致。以服务模式运行，过一段时间，或是重启电脑后，必然出现无法上网的情况。

**Comment by mokeyish** [comment]
不分流，不分组搞这么多 server 干嘛，并发 s请求浪费资源，fastest-ip 模式，还拖慢响应速度。

**Comment by mokeyish** [comment]
理论上非加密的更快，没啥影响是因为有缓存和开启了域名预读取，常用的域名过期会自动去查询很更新，这样每次查询响应都很快。
