### ISSUE TITLE
macOS 无法监听v6地址

### ISSUE THREAD

**Issue by kdurov** [mokeyish/smartdns-rs#37]
macOS 13 x64环境下。

```
bind [::1]:53
bind [::]:53
bind localhost:53
```

配置文件似乎只要监听了v6地址，就会如下报错。
麻烦检查下监听v6地址相关。谢谢。

sudo /usr/local/bin/smartdns run -c /usr/local/etc/smartdns/smartdns.conf
1677077038:INFO: Smart-DNS 🐋 0.1.9 starting
1677077038:INFO: loading configuration from: "/usr/local/etc/smartdns/smartdns.conf"
thread 'main' panicked at 'localhost:53addr expect [::]:53 or 0.0.0.0:53', src/dns_conf.rs:437:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by kdurov** [comment]
你好

我的意思是上面几种写法均会报错。

**Comment by mokeyish** [comment]
你用 `sudo smartdns-rs service stop` 来停止。
https://github.com/mokeyish/smartdns-rs/blob/1620c328973879e8c7d70262ac7314fc5c908a03/src/service/macos/mod.rs#L27-L43

---

已经提交了一个修复解析 `bind localhost:53`, 其他的好像没问题，一会自动打包新的版本。

**Comment by kdurov** [comment]
查了下 launchctl 文档。
应该是 keeplive 开启后， smartdns-rs.plist 只要 load 就会一直启动。

能够考虑修改下呢？

**Comment by mokeyish** [comment]
卸载用 `sudo smartdns service uninstall -p` -p 选项会连配置文件一起删除的。



你可以帮忙改个可用的，plist 文件出来么？之前就是好像关不掉，才用 bootout。原始文件在这 https://github.com/mokeyish/smartdns-rs/blob/main/src/service/macos/files/Library/LaunchDaemons/smartdns-rs.plist

**Comment by kdurov** [comment]
不知道照着现成改的 plist 优雅不。我就只替换了 keepalive 成 runatload 至少本地环境测试下没问题。
可以用 `sudo launchctl stop smartdns-rs` `sudo launchctl start smartdns-rs ` 来开启/关闭 smartdns 。
（说起来 launchctl 竟然没有 restart......）
已经安装的话可能需要 `sudo launchctl unload -w /Library/LaunchDaemons/smartdns-rs.plist && sudo launchctl load -w /Library/LaunchDaemons/smartdns-rs.plist` 重新加载。

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RunAtLoad</key>
	<true/>
	<key>Label</key>
	<string>smartdns-rs</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/smartdns</string>
		<string>run</string>
		<string>-c</string>
		<string>/usr/local/etc/smartdns/smartdns.conf</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

**Comment by mokeyish** [comment]
想想，keepalive 也合理，万一意外关了，它能自动启动。。。至于真的想关，就调用 smartdns service 子命令管理吧，这个 windows,linux,macos 都兼容了。

**Comment by mokeyish** [comment]
没其他问题，这个先关闭了，有问题再提。新版本在酝酿中，改了一大片，早期版本，不稳定，请见谅。
