### ISSUE TITLE
smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)

### ISSUE THREAD

**Issue by Potterli20** [mokeyish/smartdns-rs#372]
这个什么问题？
     Loaded: loaded (/etc/systemd/system/smartdns.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-09-15 18:00:23 CST; 4h 55min ago
   Main PID: 3968 (smartdns-rs)
      Tasks: 9 (limit: 9599)
     Memory: 432.5M
        CPU: 3h 21min 41.982s
     CGroup: /system.slice/smartdns.service
             `-3968 /root/smartdns/smartdns-rs run -c /root/smartdns/smartdns.conf -v

Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)
Sep 15 22:55:04 dns-1 smartdns-rs[3968]: 2024-09-15 22:55:04.162:DEBUG:smartdns::server::tcp:36: error receiving TCP tcp_stream error: No file descriptors available (os error 24)

**Comment by mokeyish** [comment]
FYI

https://stackoverflow.com/questions/39537731/errno-24-too-many-open-files-but-i-am-not-opening-files

**Comment by mokeyish** [comment]
> ```
> No file descriptors available (os error 24)
> ```
> 
> Increase your rlimit file descriptor.



https://github.com/shadowsocks/shadowsocks-rust/issues/1261
