### ISSUE TITLE
v0.8.6 预编译程序在 Windows 10 无法启动

### ISSUE THREAD

**Issue by moi-si** [mokeyish/smartdns-rs#374]
CPU 是 Intel，系统 Windows 10 22H2。

双击程序、cmd 输入`smartdns` `smartdns run`或`smartdns -test`都是
```
2024-09-15 23:21:50.233:INFO: Smart-DNS 🐋 0.8.6 🕙 Sat Jul 27 10:45:27 UTC 2024 starting
thread 'main' panicked at src\dns_conf.rs:82:18:
No configuation file found.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
运行目录下有 smartdns.conf，smartdns-x86_64-pc-windows-gnu-v0.8.6.zip 和 
smartdns-x86_64-pc-windows-msvc-v0.8.6.zip 也都试过了。

感觉跟#156 和#296 是同一个问题。

**Comment by mokeyish** [comment]
哪个目录？

你要带配置文件的参数的

**Comment by mokeyish** [comment]
@moi-si #379 这个 PR 增强了文件解析的能力，会自动查询当前 exe 所在目录的配置文件了。

方便的化，验证一下。

**Comment by mokeyish** [comment]
你用的启动命令是什么？
