### ISSUE TITLE
REQ: Add timer/worker to periodically do jobs in cache

### ISSUE THREAD

**Issue by chmichael** [mokeyish/smartdns-rs#393]
Hello,
  It's needed a timer to do the following jobs:
  
1) Save the cache to file every xx minutes.
2) Remove cached items stored for xx amount of days

Thank you

**Comment by mokeyish** [comment]
Here is a simple implementation. #395

**Comment by chmichael** [comment]
It works i set to 3600 seconds (1 hour) but it does save it twice ?

![εικόνα](https://github.com/user-attachments/assets/9889aa12-eda8-47cc-8aa8-2980817d286f)

**Comment by mokeyish** [comment]
Replace it with tokio sleep and it should work as you expect.


https://docs.rs/tokio/latest/tokio/time/struct.Sleep.html

**Comment by chmichael** [comment]
You forgot 
No 2. Remove cached items stored for xx amount of days
or it does cleanup the cache and i missed it ?

Thanks

**Comment by mokeyish** [comment]
@chmichael The second one should not be necessary. If it is read from the cache, it will be removed from the memory if it expires. It will not be there next time save it.

I don’t quite understand, what do you think?

**Comment by chmichael** [comment]
> @chmichael The second one should not be necessary. If it is read from the cache, it will be removed from the memory if it expires. It will not be there next time save it.

Ok i thought it stays forever since my cache file is only growing up.
