### ISSUE TITLE
smartdns 0.8.7 cname 使用工具解析ip失败

### ISSUE THREAD

**Issue by Ryu-Z** [mokeyish/smartdns-rs#394]
**问题现象**  
简要描述问题出现的现象
nslookup a.baidu.com
;; Question section mismatch: got www.baidu.com/A/IN
;; Question section mismatch: got www.baidu.com/A/IN
**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本
smartdns 0.8.7 mac 
4. 涉及的配置(注意去除个人相关信息)
cname /a.baidu.com/www.baidu.com

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by mokeyish** [comment]
duplicate with #385

**Comment by Ryu-Z** [comment]
发现命令行可以解析,但是浏览器访问的时候依然解析失败
