### ISSUE TITLE
DoH3不支持纯ipv6地址

### ISSUE THREAD

**Issue by zhengqwe** [mokeyish/smartdns-rs#397]
配置文件：
```
bind :53
server-h3 2001:4860:4860::8888
speed-check-mode none
```
报错
```
error resolving: proto error: error creating quic connection: invalid server name: [2001:4860:4860::8888]
```

**Comment by mokeyish** [comment]
你试试 IPv6 全地址，可能缩写不支持。

**Comment by mokeyish** [comment]
I have reported this issue to upstream, see https://github.com/quinn-rs/quinn/issues/2005

**Comment by mokeyish** [comment]
@zhengqwe This has been fixed. You can download it from here:
https://github.com/mokeyish/smartdns-rs/actions/runs/11257954547
