### ISSUE TITLE
smartdns 0.8.7 cname 仍然有问题

### ISSUE THREAD

**Issue by Ryu-Z** [mokeyish/smartdns-rs#400]
**问题现象**  
简要描述问题出现的现象
下载测试版本, 虽然命令行可以解析了, 但是发现浏览器依然使用不了cname的解析的域名
**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本
smartdns 0.8.7 mac 
4. 涉及的配置(注意去除个人相关信息)
cname /a.baidu.com/www.baidu.com

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by mokeyish** [comment]
0.8.7 未修复此问题，你是下载 nightly 版本么？

**Comment by Ryu-Z** [comment]
> 0.8.7 未修复此问题，你是下载 nightly 版本么？

是的, nslookup 可以解析, 但是浏览器还是访问失败

**Comment by mokeyish** [comment]
那应该是丢了什么东西没构造出来，或者浏览器还查询了其他DNS类型，比如 HTTPS，我也不熟，你能找到么？

**Comment by Ryu-Z** [comment]
> 那应该是丢了什么东西没构造出来，或者浏览器还查询了其他DNS类型，比如 HTTPS，我也不熟，你能找到么？

我刚刚尝试绑死hosts 220.181.38.149 a.baidu.com, 浏览器访问a.baidu.com 是可以访问到东西的, 就是非安全的

**Comment by mokeyish** [comment]
#387 修复的是未同步改写 queries section .

你用的是 nightly 版本是有这个修复的，就不知道还缺了什么，知道原因就好修改

**Comment by Ryu-Z** [comment]
> #387 修复的是未同步改写 queries section .
> 
> 你用的是 nightly 版本是有这个修复的，就不知道还缺了什么，知道原因就好修改

目前也没看出来什么, 电脑上面目前也没有抓包工具, 所以也没看出来有什么问题

**Comment by mokeyish** [comment]
#403 看看这个是否修复你的问题。

**Comment by Ryu-Z** [comment]
> #403 看看这个是否修复你的问题。
> 
> 在线构建的这里下载： https://github.com/mokeyish/smartdns-rs/actions/runs/11235631516

确实可以了, 感谢
