### ISSUE TITLE
nameserver not match a.b.sample.com as *.sample.com

### ISSUE THREAD

**Issue by xyzdev-cell** [mokeyish/smartdns-rs#432]
want to match `a.b.sample.com`
---case1:
`nameserver /*.sample.com/office`
 not work
---case2:
`nameserver /*.*.sample.com/office`
not work
---case3:
`nameserver /*.b.sample.com/office`
work
--expect:
`nameserver /*.sample.com/office` should match `a.b.sample.com`

**Comment by mokeyish** [comment]
please use 

nameserver /b.sample.com/office

or 

nameserver /sample.com/office

**Comment by mokeyish** [comment]
The prefix wildcard matches the main domain name


# prefix wild card
*-a.example.com
# only match subdomains
*.example.com
# only match the main domain name
-.example.com
Note: * and - are only supported at the beginning of the domain name. Wording in other locations is not supported.

**Comment by mokeyish** [comment]
https://github.com/mokeyish/smartdns-rs/blob/main/src/config/domain.rs
