### ISSUE TITLE
运行一段时间后程序会停止解析

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#45]
我在最新的0.2.2版本里遇到了一个奇怪的bug：
不管是以服务运行还是命令行运行，初次运行之后在nslookup命令中均无法看到smartdns，命令行运行则会报错unkown response，但是关闭命令行重开一次，或者重启服务后，一切恢复正常，nslookkup命令可以检测到smartdns，使用也没有问题，可以正常解析，但是运行一段时间后又无法解析。
更新：目前最新的0.4.1和0.3.2版本中出现了同样的情况，0.3.1和0.3.0无此问题。

**Comment by mokeyish** [comment]
是不是初始化还没完成你就测试了。我很少用 windows，可以的话，你也调试看看，什么原因。

## 环境安装

可以下载 [Microsoft C++ 生成工具 ](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)，也可以直接安装 [Microsoft Visual Studio](https://visualstudio.microsoft.com/downloads/)。

主要是下面三个组件

- MSVC v143 - VS 2022 C++ x64/x86 生成工具

- 用于 Windows 的 C++ CMake 工具

- Windows 11 SDK

  Windows 10 SDK 也是可以的。

## 开发工具
安装 VsCode 以及插件 rust-analyzer

## vscode 点击调试启动

![图片](https://user-images.githubusercontent.com/16131917/223418622-c95c6acf-69f9-4535-a862-755990f29656.png)

**Comment by zbc258** [comment]
> 是不是初始化还没完成你就测试了。我很少用 windows，可以的话，你也调试看看，什么原因。
> 
> ## 环境安装
> 可以下载 [Microsoft C++ 生成工具 ](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)，也可以直接安装 [Microsoft Visual Studio](https://visualstudio.microsoft.com/downloads/)。
> 
> 主要是下面三个组件
> 
> * MSVC v143 - VS 2022 C++ x64/x86 生成工具
> * 用于 Windows 的 C++ CMake 工具
> * Windows 11 SDK
>   Windows 10 SDK 也是可以的。
> 
> 在安装 Rust 地址：https://www.rust-lang.org/tools/install
> 
> ## 开发工具
> 安装 VsCode 以及插件 rust-analyzer
> 
> ## vscode 点击调试启动
> ![图片](https://user-images.githubusercontent.com/16131917/223418622-c95c6acf-69f9-4535-a862-755990f29656.png)

不是呀，我是之前给你提过issue那位，已经使用了好多版本了，这个版本问题尤其古怪，运行一会就不解析了，nslookup命令显示就是unknown，网站也打不开，但是任务管理器看服务显示smartdns是正在运行的，命令行运行的话也没有报错，手动重启会短暂恢复，过一会又不解析了。

**Comment by zbc258** [comment]
> 是不是初始化还没完成你就测试了。我很少用 windows，可以的话，你也调试看看，什么原因。
> 
> ## 环境安装
> 可以下载 [Microsoft C++ 生成工具 ](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)，也可以直接安装 [Microsoft Visual Studio](https://visualstudio.microsoft.com/downloads/)。
> 
> 主要是下面三个组件
> 
> * MSVC v143 - VS 2022 C++ x64/x86 生成工具
> * 用于 Windows 的 C++ CMake 工具
> * Windows 11 SDK
>   Windows 10 SDK 也是可以的。
> 
> 在安装 Rust 地址：https://www.rust-lang.org/tools/install
> 
> ## 开发工具
> 安装 VsCode 以及插件 rust-analyzer
> 
> ## vscode 点击调试启动
> ![图片](https://user-images.githubusercontent.com/16131917/223418622-c95c6acf-69f9-4535-a862-755990f29656.png)

我刚刚回退到了0.2.0版本，没有这个问题存在，配置文件未作改动。
0.2.1版本就出现了这个现象，但是重启之后就能恢复正常解析；0.2.2重启了几次都是解析一会后突然就不工作了，导致原本正常的网络连接也无法使用。

**Comment by mokeyish** [comment]
@zbc258 不用每次引用前面的一大段，不方便看。


按你这么说，可能是我把查询失败自动 fallback 删了？

提交: https://github.com/mokeyish/smartdns-rs/commit/b4d4a466e93412afda079b0081536cf0d391e169 

不过删掉这个是为了避免 DNS 泄露，不能这么自动。你可以试试还原这块代码，看看是不是这个原因。我自己苹果电脑用着都很稳定。
