### ISSUE TITLE
Prefer IPv4 or IPv6

### ISSUE THREAD

**Issue by APT-ZERO** [mokeyish/smartdns-rs#457]
Hello
How can i config smartdns-rs it to Prefer IPv4 or IPv6
I mean if there is both IPv4 and IPv6 for a domain, just send the IPv4 to client, but it there is only IPv6 then send the IPv6 to the client
or when pingtest is enabled, test IPv4 and if none of them worked, then try IPv6 IPs and send the working one back
If it is not possible, then please consider this Issue as a Feature Request
Thank you

**Comment by mokeyish** [comment]
There is a dual stack preference, when one is noticeably slower than the other one will send a SOA.

The code is implemented here

https://github.com/mokeyish/smartdns-rs/blob/main/src/dns_mw_dualstack.rs
