### ISSUE TITLE
Remote source and Auto-Update resources

### ISSUE THREAD

**Issue by APT-ZERO** [mokeyish/smartdns-rs#458]
Hello
Please add option to get the domain list from a URL and update it each day or week for example (customizable time)
And as there is many different domain list formats, please add support for more list formats
Thank you

**Comment by mokeyish** [comment]
Currently, remote reading is partially supported, but timing is not implemented.

How to configure, refer to here

https://github.com/mokeyish/smartdns-rs/blob/main/src/config/parser/domain_set.rs#L202
