### ISSUE TITLE
重开贴：大佬，最新commit的端口绑定又失效了！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#61]
commit：da2926214d3b0340fe8996dd65d3f7b570d4d1ae
1、无论是luci配置还是自定义配置（哪怕是其中一个也不行，原来的其中一个绑定可以运行），加入端口和设备绑定后不能运行，去掉端口和设备绑定却正常运行！！！
2、上游国外DOH服务器可以正常解析。。。。
3、自定义配置中测速无效。。。。
4、最新commit编译时文件是317，而原来的是318（见原来的图）：
![image](https://user-images.githubusercontent.com/45259624/226108969-eb96c16a-7844-4290-8d29-9078d460eb5f.png)

**Comment by mokeyish** [comment]
最新 commit 是解决，rustls 不支持直接 IP 上游，可能是解决（国外DOH服务器解析的问题）
上游的几个类库，全都 patch 了补丁，317 和 318 没关系。
https://github.com/mokeyish/smartdns-rs/blob/da2926214d3b0340fe8996dd65d3f7b570d4d1ae/Cargo.toml#L40-L45

---

没有动到设备绑定，设备绑定我这边都正常的，windows 和 Linux 都测试了，所以无法帮你解决。这个恐怕得你自己调试看看原因，我无法重现。

**Comment by mokeyish** [comment]
我这绑定都没问题

![图片](https://user-images.githubusercontent.com/16131917/226109746-7a165efe-a2f8-4082-bee9-1c282b9b6d1d.png)

**Comment by zxlhhyccc** [comment]
设备绑定是哪种模式？
是：
```
bind :53@设备名称
bind :53@lo 
```还是仅为：
```
bind :53@设备名称
````

**Comment by mokeyish** [comment]
就是 `ip link show` 看到的设备名，都可以填上去，如果没有 ip 地址会忽略。

**Comment by mokeyish** [comment]
Windows 就把这个 以太网填上去。

![图片](https://user-images.githubusercontent.com/16131917/226110891-24525be7-34eb-4b4a-8d30-ea7156b5cc3c.png)

**Comment by mokeyish** [comment]
你都拿到代码编译了，自己调试一下看看了。

![图片](https://user-images.githubusercontent.com/16131917/226111093-e3f76d81-7a2d-46a1-9997-d07387d96dc4.png)

**Comment by zxlhhyccc** [comment]
找到原因了，我ssrp在运行，用pdnsd在解析导致只能第二种模式，改为5335端口正常了。
现在的问题是：要么luci不要绑定端口和设备，要么自定义配置不要绑定端口和设备，如果两个都绑定，软件崩溃而不运行。。。。这个能否解决同时可以绑定呢？

**Comment by mokeyish** [comment]
为什么要删掉呢？解析配置文件失败了？

**Comment by zxlhhyccc** [comment]
> 为什么要删掉呢？解析配置文件失败了？

我搞错了，是修改这两行即可：
https://github.com/mokeyish/smartdns-rs/blob/main/src/service/linux/initd/openwrt/files/etc/init.d/smartdns-rs#L296
https://github.com/mokeyish/smartdns-rs/blob/main/src/service/linux/initd/openwrt/files/etc/init.d/smartdns-rs#L348

**Comment by mokeyish** [comment]
测速模块需要重构的，要等等。你再多试试，最后没问题了，提交个 PR 来更新 `/etc/init.d/smartdns-rs`，我自己也没放到 openwrt 上面去运行，因为功能还没完全覆盖完。

**Comment by zxlhhyccc** [comment]
> domain_set_args

`/etc/init.d/smartdns-rs`已经可以使用原版最新的init脚本了，我现在能否pr上来？

**Comment by mokeyish** [comment]
不错，那就提 PR 吧

**Comment by zxlhhyccc** [comment]
> 不错，那就提 PR 吧

请尽快修复端口和设备绑定，否则貌似会出问题：
![image](https://user-images.githubusercontent.com/45259624/226115193-ea0a7e3e-8b32-48fe-acd1-7cff9ee6afc7.png)

**Comment by mokeyish** [comment]
我没法重现，修复不了啊

**Comment by zxlhhyccc** [comment]
> 我没法重现，修复不了啊

你可否使用luci测试一下？

**Comment by mokeyish** [comment]
现在不想折腾 luci 啊，理论上跟 luci 没有关系，你前台就是用 `smartdns run -c <conf-file> -d`跑试了吗？以最小配置，测试下。

**Comment by zxlhhyccc** [comment]
最新的commit：eb6b212b6ebec342afcfbd4c802e7788fe00e6dd，无法解析国外了，油管都不通。。。。

**Comment by mokeyish** [comment]
😓，最新版改的苹果电脑 homebrew 支持，现在在 macos 上支持 `brew install samrtdns` 来安装了，大概率是你自己网络的问题。

**Comment by zxlhhyccc** [comment]
> 😓，最新版改的苹果电脑 homebrew 支持，现在在 macos 上支持 `brew install samrtdns` 来安装了，大概率是你自己网络的问题。

我回退到commit：da2926214d3b0340fe8996dd65d3f7b570d4d1ae后一切正常。。。。

**Comment by zxlhhyccc** [comment]
更新到0.4.1版本后，这又是什么问题：
````
root@OpenWrt:/usr/sbin# ./smartdns run -c ./etc/smartdns/custom.conf
1679229702:INFO: Smart-DNS 🐋 0.4.1 starting
1679229702:WARN:smartdns::dns_conf::parse:1580: configuration file "./etc/smartdns/custom.conf" does not exist
1679229702:INFO: whoami 👉 openwrt
1679229702:WARN:smartdns::dns_client:120: not bootstrap-dns found, use system_conf instead.
1679229702:INFO: listening for UDP on 0.0.0.0:53
1679229702:INFO:
1679229702:INFO:      _____                      _       _____  _   _  _____
1679229702:INFO:     / ____|                    | |     |  __ \| \ | |/ ____|
1679229702:INFO:    | (___  _ __ ___   __ _ _ __| |_    | |  | |  \| | (___
1679229702:INFO:     \___ \| '_ ` _ \ / _` | '__| __|   | |  | | . ` |\___ \
1679229702:INFO:     ____) | | | | | | (_| | |  | |_    | |__| | |\  |____) |
1679229702:INFO:    |_____/|_| |_| |_|\__,_|_|   \__|   |_____/|_| \_|_____/
1679229702:INFO:
1679229702:INFO: awaiting connections...
1679229702:INFO: server starting up
^C1679229710:INFO: terminating...
1679229710:INFO: SmartDNS 0.4.1 shutdown
`````

**Comment by mokeyish** [comment]
嗯，配置文件不存在，应该直接退出程序，不继续执行。

**Comment by zxlhhyccc** [comment]
> 嗯，配置文件不存在，应该直接退出程序，不继续执行。
无法启动。提示：`dns_client:120: not bootstrap-dns found, use system_conf instead.`
````
root@OpenWrt:/usr/sbin# ./smartdns run -c /etc/smartdns/custom.conf
1679231817:INFO: Smart-DNS 🐋 0.4.1 starting
1679231817:INFO: loading configuration from: "/etc/smartdns/custom.conf"
1679231817:INFO: whoami 👉 smartdns
1679231817:INFO: upstream server: udp://1.12.12.12 [Group: china]
1679231817:INFO: upstream server: udp://101.6.6.6 [Group: china]
1679231817:INFO: upstream server: udp://101.226.4.6 [Group: china]
1679231817:INFO: upstream server: udp://119.29.29.29 [Group: china]
1679231817:INFO: upstream server: udp://123.125.81.6 [Group: china]
1679231817:INFO: upstream server: udp://180.76.76.76 [Group: china]
1679231817:INFO: upstream server: udp://202.101.224.69 [Group: china]
1679231817:INFO: upstream server: udp://202.38.93.153 [Group: china]
1679231817:INFO: upstream server: udp://202.141.162.123 [Group: china]
1679231817:INFO: upstream server: udp://202.141.178.13 [Group: china]
1679231817:INFO: upstream server: udp://223.5.5.5 [Group: china]
1679231817:INFO: upstream server: udp://9.9.9.9 [Group: default]
1679231817:INFO: upstream server: udp://64.6.64.6 [Group: default]
1679231817:INFO: upstream server: udp://64.6.65.6 [Group: default]
1679231817:INFO: upstream server: udp://76.76.19.19 [Group: default]
1679231817:INFO: upstream server: udp://101.101.101.101 [Group: default]
1679231817:INFO: upstream server: udp://208.67.222.222 [Group: default]
1679231817:INFO: upstream server: udp://208.67.220.220 [Group: default]
1679231817:INFO: upstream server: tls://dns.google [Group: default]
1679231817:INFO: upstream server: https://dns.google/dns-query [Group: default]
1679231817:INFO: upstream server: tcp://1.0.0.1 [Group: default]
1679231817:INFO: upstream server: tcp://8.8.8.8 [Group: default]
1679231817:INFO: upstream server: tcp://149.112.112.112 [Group: default]
1679231817:INFO: upstream server: tls://1dot1dot1dot1.cloudflare-dns.com [Group: default]
1679231817:INFO: upstream server: tls://dns.google [Group: default]
1679231817:INFO: upstream server: tls://dns.adguard.com [Group: default]
1679231817:INFO: upstream server: tls://dns.twnic.tw [Group: default]
1679231817:INFO: upstream server: tls://185.222.222.222 [Group: default]
1679231817:INFO: upstream server: tls://185.184.222.222 [Group: default]
1679231817:WARN:smartdns::dns_client:120: not bootstrap-dns found, use system_conf instead.
thread 'main' panicked at 'could not bind to udp: 0.0.0.0:53', src/main.rs:274:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```````

**Comment by mokeyish** [comment]
你把完整配置文件发给我，我试试。

系统会先搜索 `-bootstrap-dns` 的为 bootstrap-dns，如果没有标记，会去找那些纯 Ip 的作为 bootstrap-dns，如果还没有，就使用系统网卡分配的。

---

监听不了端口，是端口被占用。

**Comment by zxlhhyccc** [comment]
我把53端口释放后能启动，但luci是自动释放53端口的，可是在luci下运行一下就停止了，可是0.4.0版本却正常，这是什么情况？

**Comment by zxlhhyccc** [comment]
> -bootstrap-dns

**`-bootstrap-dns`**该如何标记？

**Comment by mokeyish** [comment]
https://pymumu.github.io/smartdns/config/bootstrap-dns/

**Comment by zxlhhyccc** [comment]
> https://pymumu.github.io/smartdns/config/bootstrap-dns/

这种格式可以吗？
````
![image](https://user-images.githubusercontent.com/45259624/226179299-e879e966-52a4-40cd-a295-93b2058f172c.png)

**Comment by zxlhhyccc** [comment]
域名规则貌似有点问题，好像只能读取一个参数。。。。

**Comment by zxlhhyccc** [comment]
> 能描述准确点么，怎么重现？定位不了问题，等于白说。。。

我提了pr。你看一下启动脚本的299-300行，这是我添加的，意思是判断如果域名规则列表为空或者没有域名规则列表，则返回。

**Comment by mokeyish** [comment]
> 我提了pr。你看一下启动脚本的299-300行，这是我添加的，意思是判断如果域名规则列表为空或者没有域名规则列表，则返回。

你这直接返回，把最后面那个也给忽略了

**Comment by zxlhhyccc** [comment]
> > 我提了pr。你看一下启动脚本的299-300行，这是我添加的，意思是判断如果域名规则列表为空或者没有域名规则列表，则返回。
> 
> 你这直接返回，把最后面那个也给忽略了

是的啊，那是域名规则列表为空是就忽略，为空还要读取干嘛？在域名规则列表不为空时，就执行后面的命令，错了吗？

**Comment by zxlhhyccc** [comment]
大佬，有个问题提一下，编译后在安装二进制文件时，提示二进制没有文件头，这是什么情况？虽然不影响使用。。。。

**Comment by mokeyish** [comment]
没遇到过，不清楚
