### ISSUE TITLE
domain-set 不工作？

### ISSUE THREAD

**Issue by PikuZheng** [mokeyish/smartdns-rs#78]
最新代码自编译。配置文件主要如下：
```
dualstack-ip-selection no
cname /services.googleapis.cn/services.googleapis.com
domain-set -name google -file /etc/smartdns/google.txt
domain-rules /domain-set:google/ -speed-check-mode none -nameserver outbound -address #6
```
其中 /etc/smartdns/google.txt 文件：
```
googleapis.cn
googleapis.com
google.com
.......
```
测试
```
# nslookup www.google.com
服务器:  UnKnown
Address:  xxxxxxx

非权威应答:
名称:    www.google.com
Addresses:  2404:6800:4004:80f::2004                <------------------ ipv6结果预期没有（-address #6）
          142.251.222.4

# nslookup services.googleapis.cn. 
服务器:  UnKnown
Address:  xxxxxxxx

名称:    services.googleapis.com
Addresses:  2404:6800:4004:822::200a                 <------------------ ipv4结果没有了
          2404:6800:4004:812::200a
          2404:6800:4004:81d::200a
          2404:6800:4004:821::200a
```

**Comment by mokeyish** [comment]
意思 “#6” 没生效是么？

https://github.com/mokeyish/smartdns-rs/blob/4a2befdde1d228876aee4c33423af7695bfc30fa/src/dns_mw_addr.rs#L105

**Comment by PikuZheng** [comment]
现在不确定是 domain-set 匹配问题还是 address # 6问题

**Comment by mokeyish** [comment]
嗯，我这周末加上，中间件的 mock ，方便于做单元测试，这种问题，碰到一个就加上单元测试。

**Comment by zxlhhyccc** [comment]
@PikuZheng @mokeyish `domain-set`好像是不工作，我上传了域名规则文件，但没反应。。。
另外，大佬域名屏蔽功能上了吗？我设置了要屏蔽的域名，但仍可以登录域名网页。。

**Comment by mokeyish** [comment]
规则树是在这窗口的，domain_set 会展开，这里没有判断冲突覆盖的问题，你们是不是有覆盖的情况？


https://github.com/mokeyish/smartdns-rs/blob/e96c4577e8cff1ff810e96e93eb7dba9bbd25353/src/dns_rule.rs#L31-L39

**Comment by PikuZheng** [comment]
主要是日志中没有匹配到规则的记录，难以判断是规则匹配问题还是规则生效问题

**Comment by PikuZheng** [comment]
domain-rule读domain-set展开是正确的，上游组(-nameserver outbound)生效了。
`domain-rule /google.com/ -address #6` 也不生效。
`address /google.com/#6` 是生效的。

**Comment by mokeyish** [comment]
明白了，`#6` 前面有空格，被当成注释干掉了。

**Comment by mokeyish** [comment]
@PikuZheng 已经修复了，请验证一下，没问题关了这个 issue

**Comment by PikuZheng** [comment]
> @PikuZheng @mokeyish `domain-set`好像是不工作，我上传了域名规则文件，但没反应。。。 另外，大佬域名屏蔽功能上了吗？我设置了要屏蔽的域名，但仍可以登录域名网页。。

你要是用的luci，可能是luci问题。。。domain-rule的-address #（域名屏蔽）正常了
