### ISSUE TITLE
init脚本还是存在一点问题，原版代码与这几行代码不同！

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#90]
原版代码与这几行代码不同！如果是原版代码，会导致无法运行，但这里的几行判断代码会导致此项目不能使用转发规则文件，怀疑还是源码存在问题！
项目里的init脚本代码：
https://github.com/mokeyish/smartdns-rs/blob/main/contrib/openwrt/conf/smartdns.init#L299-L303
原版的init脚本代码：
https://github.com/pymumu/smartdns/blob/master/package/openwrt/files/etc/init.d/smartdns#L299-L300

**Comment by mokeyish** [comment]
除了启动命令，其他的保持一样就好了。有问题找到问题原因，解决即可。

**Comment by zxlhhyccc** [comment]
> 除了启动命令，其他的保持一样就好了。有问题找到问题原因，解决即可。

脚本的原版那两行不修改，绝对启动不了。。。

**Comment by zxlhhyccc** [comment]
> 除了启动命令，其他的保持一样就好了。有问题找到问题原因，解决即可。

大佬，请您看一下脚本。。。

**Comment by PikuZheng** [comment]
# 6 这个是我提那个bug，已经修了。。

**Comment by zxlhhyccc** [comment]
> `#6` 应该是我提那个bug，已经修了。新版试试？ 您是用smartdns的luci配rust程序？

是的，脚本我昨晚修了，大佬合并了。
但是有个问题，域名屏蔽在luci下的配置无效，添加了需屏蔽的域名，但却没有屏蔽，不知道为什么。。。

**Comment by PikuZheng** [comment]
domain-rule 的 -address # 不起作用，但address /域名/# 正常的问题。0.51起正常
