### ISSUE TITLE
windows 下运行一段时间后会停止解析，导致无法上网

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#91]
平台：Windows11
问题：在最新的0.5.0版本中，运行一段时间后停止解析的问题依然存在，或者说从0.3.2版本开始就一直没有解决，而0.3.1版本中没有该问题。
不管是以服务方式还是命令行方式运行，几分钟后用nslookup命令查看，均不会显示smartdns，同时网络也无法正常访问。
重启服务后会短暂恢复，但几分钟后会再次停止。

**Comment by mokeyish** [comment]
可能是 ipv6 查询的问题。你加上这个配置
```ini
force-AAAA-SOA yes
```

**Comment by mokeyish** [comment]
不是这个 ipv6 查询的原因，但已经可以重现了，可能需要一段时间来找到根源，解决

**Comment by zbc258** [comment]
> 不是这个 ipv6 查询的原因，但已经可以重现了，可能需要一段时间来找到根源，解决

好的，期待早日解决。

**Comment by mokeyish** [comment]
@zbc258 你看下 0.5.1 版本有没有修复，上游类库，是有个死循环的 bug，我修复了。

不过还有个查询 timeout (` nslookup -qtype=a lan.lan. ::1`)的问题，linux 下没问题，windows 下会卡死。不知道你遇到的是 死循环退出的问题，还是这个 timeout 导致卡死的问题。

**Comment by zbc258** [comment]
> @zbc258 你看下 0.5.1 版本有没有修复，上游类库，是有个死循环的 bug （[这里查看](https://github.com/mokeyish/trust-dns/commit/6ee9e69fb32cf48c4edf36742a3e2c9451dabd14)），我修复了。
> 
> 不过还有个查询 timeout (` nslookup -qtype=a lan.lan. ::1`)的问题，linux 下没问题，windows 下会卡死。不知道你遇到的是 死循环退出的问题，还是这个 timeout 导致卡死的问题。

正在试，好像还没有，命令行运行了两三分钟nslookup又看不到smartdns了。

**Comment by mokeyish** [comment]
看来是查询不存在的域名 timeout 结果就卡死了。不过 linux 下一直没问题，windows 就会这样，奇怪了

**Comment by PikuZheng** [comment]
linux可能也有这个问题，感觉会线程阻塞什么的，但是几秒后就恢复了

**Comment by mokeyish** [comment]
@zbc258 @PikuZheng 看看 0.5.2 版本是否修复了。我本地验证没问题了。

**Comment by PikuZheng** [comment]
刚更新的那个吗？我点了编译，现在已经躺倒了，明天试。

**Comment by mokeyish** [comment]
是的，上游类库的一个 bug, udp 是无状态的，不应该因为一个错误就退出监听，改成 continue 就好了。

![图片](https://user-images.githubusercontent.com/16131917/227973438-15844c9b-ca7d-4a6a-b468-645424aa8733.png)

**Comment by zbc258** [comment]
> 是的，上游类库的一个 bug, udp 是无状态的，不应该因为一个错误就退出监听，改成 continue 就好了。
> 
> ![图片](https://user-images.githubusercontent.com/16131917/227973438-15844c9b-ca7d-4a6a-b468-645424aa8733.png)
0.5.2版本运行正常，感谢各位的耐心解答。
