### ISSUE TITLE
默认地址[::]无法监听，导致示例配置文件失效

### ISSUE THREAD

**Issue by zbc258** [mokeyish/smartdns-rs#92]
若配置文件中监听地址设为[::]，命令行运行会报错，必须改为[::1]才能监听。这也导致example文件夹中提供的配置文件示例无法直接拿来使用，希望能够更新配置文件的示例。
还有，localhost什么时候改成只监听127.0.0.1的？一开始没反应过来，拿命令行运行一次才知道现在localhost不会同时监听[::1]了，还是以前同时监听用着方便一些。

**Comment by mokeyish** [comment]
windows wsl 会占用 53 端口。会导致启动不了。

**Comment by zbc258** [comment]
> windows wsl 会占用 53 端口。会导致启动不了。

诶？但是我电脑把WSL关了呀，我的是win11和ubuntu双系统，之前用过WSL但是后来删掉了。

**Comment by mokeyish** [comment]
那你查一下，53 被哪个程序占用了。`[::]` 是监听 ipv6 所有地址，如果已经有地址监听了，会报错，这也是为什么 `[::1]` 没问题了。

**Comment by zbc258** [comment]
> 那你查一下，53 被哪个程序占用了。`[::]` 是监听 ipv6 所有地址，如果已经有地址监听了，会报错，这也是为什么 `[::1]` 没问题了。

奇怪，用netstat -aon|findstr "53"查了一下不管tcp、udp，都没有直接占53的，只有占5353这种的。

**Comment by mokeyish** [comment]
> 还有，localhost什么时候改成只监听127.0.0.1的？一开始没反应过来，拿命令行运行一次才知道现在localhost不会同时监听[::1]了，还是以前同时监听用着方便一些。

跟原 c 版保持一致了，不同时监听 ipv4 和 ipv6。
https://pymumu.github.io/smartdns/config/basic-config/

![图片](https://user-images.githubusercontent.com/16131917/227783386-5415251d-a655-42a9-a6b0-338d701442be.png)

---
---

我后面再看看 `localhost:53` 和 `*:53` 同时监听 ipv4 和 ipv6 吧

**Comment by zbc258** [comment]
> > 还有，localhost什么时候改成只监听127.0.0.1的？一开始没反应过来，拿命令行运行一次才知道现在localhost不会同时监听[::1]了，还是以前同时监听用着方便一些。
> 
> 跟原 c 版保持一致了，不同时监听 ipv4 和 ipv6。 https://pymumu.github.io/smartdns/config/basic-config/
> 
> ![图片](https://user-images.githubusercontent.com/16131917/227783386-5415251d-a655-42a9-a6b0-338d701442be.png)
> 
> 我后面再看看 `localhost:53` 和 `*:53` 同时监听 ipv4 和 ipv6 吧

有点玄学，重启了一下电脑又可以监听了。
