### ISSUE TITLE
MacOS bind address already in use.

### ISSUE THREAD

**Issue by HFSstaff** [mokeyish/smartdns-rs#95]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/107898337/227921603-fdd5fcb1-138e-4ee5-b432-45543b1cd1f1.png">

bind监听端口：
bind :8051@en0

使用bind :8051时，可以正常使用本机回环地址查询dns；
选定网口en0时，无法在本机上使用本机回环地址、局域网地址进行查询，局域网其他设备也无法进行dns查询，无log输出。

**Comment by mokeyish** [comment]
没看明白什么意思。
苹果电脑，要监听本地和局域网 bind 两次就是了。

```shell
bind :53@lo0  # 会去找网卡名是 lo0 的 Ipv4 地址
bind :53@en0  # 会去找网卡名是 en0 的 Ipv4 地址
```

**Comment by HFSstaff** [comment]
使用以下配置之后，看日志可以正常本地回环和局域网地址了。
```
bind :8053@lo0  # 会去找网卡名是 lo0 的 Ipv4 地址
bind :8053@en0  # 会去找网卡名是 en0 的 Ipv4 地址
```
使用dig查询本地回环地址时，`dig www.baidu.com @127.0.0.1 -p 8053`，可以正常获得smartdns的回应，
但是使用局域网地址查询时，`dig www.baidu.com @192.168.2.180 -p 8053`，却无法获得smartdns回应。
![image](https://user-images.githubusercontent.com/107898337/227938515-e547100c-80a8-4e86-985e-aec9c5187bbb.png)

**Comment by mokeyish** [comment]
防火墙？

**Comment by HFSstaff** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/107898337/227943525-c59d4937-222b-49a0-ac27-488144feb39b.png">

smartdns已放行

**Comment by mokeyish** [comment]
嗯，我找时间查下原因。

**Comment by mokeyish** [comment]
> 我这里都正常啊

@PikuZheng 你也是 mac 电脑？

**Comment by HFSstaff** [comment]
局域网中的其他电脑也无法通过本机IP（192.168.2.180）查询dns，一样超时。

这里改端口了，因为也有个问题：mac端smartdns运行终止之后，无法再次使用终止前的端口，所以得改端口后再测速。
经`sudo lsof -i:port`查看后，无法运行的端口也没有占用。
```
dig www.baidu.com @192.168.2.180 -p 8050

; <<>> DiG 9.14.10 <<>> www.baidu.com @192.168.2.180 -p 8050
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
ping 192.168.2.180

正在 Ping 192.168.2.180 具有 32 字节的数据:
来自 192.168.2.180 的回复: 字节=32 时间=41ms TTL=64
来自 192.168.2.180 的回复: 字节=32 时间=60ms TTL=64
来自 192.168.2.180 的回复: 字节=32 时间=67ms TTL=64
来自 192.168.2.180 的回复: 字节=32 时间=2ms TTL=64

192.168.2.180 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 2ms，最长 = 67ms，平均 = 42ms
```

**Comment by mokeyish** [comment]
你用了其他会修改路由的软件吗？例如用了 tun/tap

**Comment by mokeyish** [comment]
我这重启，并用 `brew upgrade smartdns` 更新版本后，再用其他机器访问，就弹窗提示要不要通过防火墙，选择允许就正常了。

可能是先前没点击允许通过防火墙？

**Comment by PikuZheng** [comment]
啊这 我是下载的release运行的，手动加的这个程序进防火墙。
brew会对应用签名吧？应该是差在这里了。

但是还有一个问题，是smartdns结束运行后不能再次监听同一个端口。

这应该是两个不同的事情。一个是防火墙问题，另一个是进程问题。

**Comment by mokeyish** [comment]
关了不能再监听同一个端口，令人费解，很早之前遇到过，后来使用 `127.0.0.1`，没用 `0.0.0.0` 就好像再也没有遇到过。好像是 macos 独有的问题，完全没解决思路啊。

还有个问题也是费解的？就是如果监听 0.0.0.0 系统会用 ipv6 兼容的类似 ffffff.127.0.0.1 地址访问，这样程序收的到 request ，但是 response 发出去客户端收不到。

**Comment by mokeyish** [comment]
> 但是还有一个问题，是smartdns结束运行后不能再次监听同一个端口

这问题重现的步骤是:
- 监听局域网 ip ，
- 远程机器访问，
- 弹窗提示防火墙是否允许，不点击允许，也不点击拒绝，忽略弹窗。(关键步骤)
- 关闭程序，再也不能绑定原来端口
- 解决办法，重启电脑。

好像没得解决了，这是 mac 系统的原因，防火墙选择允许，就不会出现不能再绑定同一个接口了。

@PikuZheng 你再确认下？是不是只有这步骤百分百重现？

**Comment by mokeyish** [comment]
大概是 macos 系统本人的 bug。
这个 go 写的也有类似的问题 Address already in use 
https://github.com/ethereum/go-ethereum/issues/18443

**Comment by PikuZheng** [comment]
我测试的步骤和楼主的类似。将smartdns加入到防火墙允许后。运行smartdns。
此时如果没有传入连接，一切正常。如果有传入连接（但是smartdns没有收到数据），smartdns退出后，netstat仍显示端口占用。

**Comment by HFSstaff** [comment]
该问题重现的步骤是在macOS上使用自行编译和release版本：

监听局域网 ip ，
远程机器访问，
自行编译和release版本都无防火墙弹窗。此时关闭程序，可以绑定原来端口；
手动添加自行编译和release版本通过防火墙，远程机器无收到回应，smartdns无log输出，此时关闭程序，不能绑定原来端口，解决办法，重启电脑。

设置rr-ttl-min 300，但连续两次查询的ttl值都不对。

```
dig www.baidu.com @127.0.0.1 -p 8055
; <<>> DiG 9.10.6 <<>> www.baidu.com @127.0.0.1 -p 8055
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57479
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.			IN	A

;; ANSWER SECTION:
www.a.shifen.com.	64	IN	A	120.232.145.185

;; Query time: 98 msec
;; SERVER: 127.0.0.1#8055(127.0.0.1)
;; WHEN: Fri Mar 31 19:24:29 CST 2023
;; MSG SIZE  rcvd: 63

```
```
 dig www.baidu.com @127.0.0.1 -p 8055

; <<>> DiG 9.10.6 <<>> www.baidu.com @127.0.0.1 -p 8055
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1356
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.			IN	A

;; ANSWER SECTION:
www.a.shifen.com.	179	IN	A	120.232.145.144

;; Query time: 46 msec
;; SERVER: 127.0.0.1#8055(127.0.0.1)
;; WHEN: Fri Mar 31 19:24:30 CST 2023
;; MSG SIZE  rcvd: 63
```

**Comment by mokeyish** [comment]
@HFSstaff ttl 的问题，已修复，并添加了单元测试。你可以验证下

https://github.com/mokeyish/smartdns-rs/blob/9234d0d9086f238badac1a87fc9bfb55bf4327eb/src/dns_mw_addr.rs#L184-L192

**Comment by mokeyish** [comment]
@HFSstaff pymumu 已在 #116 修复，请验证一下。
